### ISSUE TITLE
extension goes off its own

### ISSUE THREAD

**Issue by yoges9** [rainforestapp/tester-chrome-extension#73] opened 2016-02-14 07:16 UTC
since 2-3 days rainforest chrome-extension goes off its own ,and i need to switch it on evey time ?

**Comment by marius11** [comment] 2016-02-14 13:12
That's an anti-idle feature introduced 2 days ago when the extension was updated.

**Comment by zeddbd** [comment] 2016-02-14 15:56
This update so awful.
Why the developer not change notify with play sound if work open in new tab ? They give a little time and then turn off extension.
Before, status of extension always show YES and can't open work tab, they didn't fix. 
One week one change and the tester so tired, it's not good, not better because the extension very awful.
Change the time off extension is silly.

**Comment by mkdige** [comment] 2016-02-14 23:32
OK, the purpose is not to get notified when you are not active on the net. Could you at least extend the active time, extension goes off in less then 10 minutes of non-activity

**Comment by facomega** [comment] 2016-02-15 19:20
why turn off a notifier?
what's the point?
it's not our fault RF don't send us work to do...
at least make the notifier notifies us when it turns off

**Comment by shrestha15207** [comment] 2016-02-15 19:51
this is the worst update. bring back the notifier that dont turn off.

**Comment by jguerrero2** [comment] 2016-02-15 20:22
The latest changes have been the worst!
Before I had more than 15 daily hits, now I just do 4 or 5 hits per day.
I have more than an hour waiting for a hit and nothing!
But if I'm not active for 10 min the extension turns off!

**Comment by pscohn** [comment] 2016-02-16 17:46
We're looking at a new way to handle idleness, but for now I'm closing this issue as it's expected behavior.

**Closed by pscohn** 2016-02-16 17:46 UTC
