### ISSUE TITLE
Rules contradictions?

### ISSUE THREAD

**Issue by kwimy** [rainforestapp/tester-chrome-extension#478] opened 2016-09-08 12:20 UTC
Hi.
It seems that there are certain contradictions in the rules or things that aren´t very clear.
For example: 
From the Wiki:
When asked to Click on the edit button and there is a button with a pencil icon, that is OK. Answer Yes.

From the last AMA (August 2016):
**Hello First i would thanks all team Rainforest for the hard work. I have a few questions and i want to get some clarification. When the instructions say Click the button on the top left that shows "New test" or a "+" sign. and there are only a "+ New test" button should we report it?**

**- Yes, you should report it. What you see on the website you be exactly what you see in one quoted instruction, not the combination of two quotes.** 

Then,what should we do? 
An icon of a pencil shouldn´t be reported and an icon of + should be reported? and what about the rest of icons?
Or is it better to use common sense and shouldn´t report any of the two cases?

In the case of the test with the instructions "New test" it´s clear which button refers although the + sign isn´t included in the instructions,in the case of pencil it´s also clear which button refers the instructions.

I´ve also doubts regarding this issue presented in the AMA:

**Hello When the instructions say Are you brought to a new test page with the title "Unnamed Test", but "Unnamed Test" does not exactly match "#1234 Unnamed Test" should we report it?**

**- Yes, if the tester author didn’t use a placeholder in the quotes before Unnamed Test, you should report it.**

This is my reasoning:
I don´t agree because if you try to edit the title of this test, the number #1234 can´t be edited, if you hover your mouse over the title, Unnamed Test is underlined because it´s the editable part, the number isn´t underlined, so I think the number isn´t part of the title.

**Comment by maciejgryka** [comment] 2016-09-08 12:43
Hey @kwimy - in the first case, there are no quotes around the edit button in the step description, which means that the test author doesn't care about what exactly the button is called. The important thing there is that you click a button that allows you to edit stuff, and the pencil buttons does that. In the second case there are quotes around "New test", which means the test author wants you to verify **exactly** what the button says. The quotes are extremely important!

In the second question, whether you can edit parts of the test title or not is irrelevant - the **only** important thing is whether you can see the text on the page exactly as it appears in quotes. If the test author doesn't care about #1234 they can use a placeholder and write "_ Unnamed test" instead.

**Comment by euparkeria** [comment] 2016-09-08 12:57
So in this case if the Instructions say "Click the "Subscribe" button" we should Select "NO" because there is an icon of a speaker in the button?
![subs](https://cloud.githubusercontent.com/assets/6674644/18350068/cd8c6e8e-75dc-11e6-85e9-bef3d3ab3edc.png)

**Comment by kwimy** [comment] 2016-09-08 13:21
Hi @maciejgryka - you´re right, shortly after writing I realized that isn´t the same case.
I think it's relevant because if the author writes Are you brought` to a new test page With the title "Unnamed Test", it´s important to know whether the number is considered part of the title or not.

In the case of "New test" I know that the quotes are extremely important but then most hits must be reported by such instructions and in this particular case and in many others I believe that the purpose of the test isn´t to check whether the button is in one form or another and that does not mean that I´m not reporting these hits because I'm doing.

**Comment by maciejgryka** [comment] 2016-09-08 13:24
@euparkeria in this case the speaker is an icon, it's not really part of the text, so if they ask for the "Subscribe" button, you should answer "Yes" and pass this (it doesn't really make sense to include images as part of the text). The "+ New Test" is slightly different, since you can easily type this out and "+" is part of the text.

As far as I know such edge cases don't happen too often, but I can see how confusing they can be. The important thing to remember is that it's better to be careful and select "No" if you're in doubt.

**Comment by maciejgryka** [comment] 2016-09-08 13:27
@kwimy cool, glad you figured it out. As a general advice never assume you know what the purpose of the test is (we often don't know that ourselves). Only customers can say what the purpose is, so our **only** task is to follow the rules exactly and report anything that doesn't match.

**Comment by rnfrst** [comment] 2016-09-08 13:29
> In the second case there are quotes around "New test", which means the test author wants you to verify exactly what the button says. The quotes are extremely important!

How is this different then with the reply from the training related hits: 

> If you are asked if the page says “Google” and you can see “Google” as a title and a bunch of other things below, answer “Yes”, because the page does say “Google”, even though it also contains other things.

If the instruction says, Does the button say "Report"? and the button contains other text or icon pretending like text just like this: "Report >", that means it has to be reported although ">" is not inside the quote?

Therefore, if the instruction says, Does the page say "Google"? and the page contains -Google test page-, then it should also be reported as opposed to the reply in the training hits because the instruction is asking about the page?

And finally, why do we have to report texts that are not inside the quotes when the rule is asking to match text from the instruction to the site we are testing?

**Comment by euparkeria** [comment] 2016-09-08 13:30
@maciejgryka In the "New Test" button that @kwimy is talking about the "+" is also an icon, not a text. Should we report that because the Icon is of a character that can be typed?

**Comment by maciejgryka** [comment] 2016-09-08 13:33
@euparkeria Yes, this is the distinction. "+" might look like an icon, but it could just as easily be text and it's trivial for test authors to add it to the step description if they want to.

**Comment by maciejgryka** [comment] 2016-09-08 13:40
@rnfrst it's different, because buttons are tiny and pages are huge! It's not reasonable to expect that the test author will specify everything you see on the whole page so as long as the text they're asking for is there, you should pass it. Buttons on the other hand have 1-2 words so if they contain some unexpected text, you should answer "No".

With all that being said, I can totally see how we're now getting into very nitty-gritty and unintuitive details. We'll think about how to update the wiki (and maybe even the rules and training) to make it more straightforward. Thanks for your patience on this and asking the hard questions!

**Comment by euparkeria** [comment] 2016-09-08 13:53
Ok, just want final clarification. 
In the image bellow, if the question is: 'Click on the "Tests" button in the navbar', we should answer YES?

And if the question is:'Click on the "New Test"button in the navbar with the plus sign', we should answer NO because the plus icon is also an ANSI character? 

Is this correct?

![rain](https://cloud.githubusercontent.com/assets/6674644/18351818/5e32c1a2-75e4-11e6-8c6e-934800bd9e06.png)

**Comment by rnfrst** [comment] 2016-09-08 14:03
@maciejgryka , sorry for giving you hard questions :), we just need to make it crystal clear because we're getting different answers over time about these rules... Remember that you were asked about the placeholder, and the question raised was the other way around wherein the instruction and the quote just say "Users Online" without the number inside the quote? You said that the tester should pass and the fact that there's something else afterwards doesn't matter.

**Comment by sheeanaa** [comment] 2016-09-08 14:06
but the "+" is in white circle and it's look like graphic icon... you can't enter symbol like that... and it's not obviously only "+"

**Comment by Vittalev** [comment] 2016-09-08 14:43
So we should also report this as "NO", right?

![test](https://cloud.githubusercontent.com/assets/22078781/18353679/5b93741c-75b9-11e6-9512-bf401405911d.jpg)

**Comment by ruben767** [comment] 2016-09-08 14:52
What about this???

![ej 1](https://cloud.githubusercontent.com/assets/20371035/18353758/492ad976-75b1-11e6-8635-166bb2d3777a.png)

The "?" is not part of the text, it also reacts like a button when hovering over it... But it can be typed. Do we have to report?

![ej 2](https://cloud.githubusercontent.com/assets/20371035/18353760/4b3c2904-75b1-11e6-912f-d12791ee6e9d.png)

This one is similar to the "#1234 Unnamed" test issue... The "Actions" text clearly belongs to a different column on the table, but it's still near the link mentioned on the instructions (The same happens with the #1234 Unnamed test).

**Comment by maciejgryka** [comment] 2016-09-08 15:29
@euparkeria: @sheeanaa basically is right, the "inverted plus" is not something you can type.

@rnfrst thanks for bringing this up! Do you have a reference for the "Users Online" thing? The wiki has this example, but with a placeholder, which makes sense. I might've answered something incorrectly earlier on, but can't find this now.

**Comment by euparkeria** [comment] 2016-09-08 15:38
@maciejgryka Thanks for clearing this up. I suspected as much and have never failed that step because of the plus but you should be aware that in the clixsense forum there are a lot of people that are confused about this step and insist the step should be failed.

**Comment by maciejgryka** [comment] 2016-09-08 15:39
@Vittalev Correct, in this case you should answer "No". As you can see we sometimes mess up our own tests :) So it's important that you report such things and we can fix them.

**Comment by maciejgryka** [comment] 2016-09-08 15:39
@euparkeria thanks for the info! It's very useful to know which parts we're failing to make clear.

**Comment by maciejgryka** [comment] 2016-09-08 15:42
@ruben767 It can't really be typed, because it has this black circle around it. It's the same case as @sheeanaa answered above. We'll try to make tests like this more clear (for example in this case the test author should probably get rid of the quotes to make it clear that they don't care about additional things next to the text,).

**Comment by rnfrst** [comment] 2016-09-08 15:42
@maciejgryka It's a follow-up question in facebook, where you posted the placeholder rule.

**Comment by Electroglitch** [comment] 2016-09-08 15:52
Unnamed test is clearly in bold! So it's pretty obvious that it's separated from #1234 number next to it 
and if you click to edit it you can only edit text (Unnamed test) not #1234 so everything is OK
![ovo](https://cloud.githubusercontent.com/assets/20214066/18356451/faca03a6-75ec-11e6-8d27-892e6e5a0779.PNG)

**Comment by ikjt** [comment] 2016-09-08 15:54
@maciejgryka , sorry for asking more questions, but this is getting very confusing. Having a clear rule where to draw the line exactly would really help.

Few more examples:

![rf02](https://cloud.githubusercontent.com/assets/22079118/18355395/a34a7700-75f1-11e6-8a29-1a79a7d73eed.jpg)

1. In the image above, if "#9000862   **Test**" is all considered as a test title now, even though they seem different elements to me, are we now supposed to fail API tests that ask us to change the test title? There are few that come to mind like Halloween, Default Browser Test, Regression. We are obviously not able to change #9000862 part, and if that is considered as part of the test title, we are failing to change the whole test title. 

2. Below the test title is Test URL:  http://www.example.org. There is an API test that asks to change the default URL to http://new.example.com. In that test question, the new URL is not in quotes, but if the question asked if the test URL changed to "http://new.example.com" in quotes, do we need to fail the step because Test URL: part is not included in quotes. To me they are different elements once again, like in previous case with the test name.

3. And as already mentioned, the question mark - there is "Preview Test" in many API test, but it has ? after it in circle, which looks like an icon and not something we can type. There are many cases like that in API tests.
Just saw your new answer to the + sign icon, so I'm assuming question mark icon falls in same category and we don't have to report it.

Thanks again for clarifying.

**Comment by Vittalev** [comment] 2016-09-08 16:07
Close the popup clicking on the "X" at the top right of it.
![wpf-usepopuptodisplayahyperlink](https://cloud.githubusercontent.com/assets/22078781/18356787/9ce40408-75c4-11e6-9cb3-aa7fc161ecd6.PNG)

Is this a "NO"? If so, naturebox tests are all wrong too.

**Comment by kwimy** [comment] 2016-09-08 16:36
@maciejgryka Why should report this hit? (which Vittalev has said) 
Does the environment still say "(default)"?
The environment is 164182119 (in that xample) and says (default)
The question should be Does the environment still say "164182119 (default)"?

**Comment by JPierreS** [comment] 2016-09-08 20:51
The situation around the ICONS or any non alpha numerical text that can be entered or pasted is clear now, but does this also apply to icons or any items in between, for instance:

Do you see "SuperDuperTester rankings"

but on the page you can see a trademark icon or any non text icon between superdupertester and rankings, should we ignore any non text and pass test ?  What about some special characters we can type on keyboard using ALT, we cannot be expected to memorise all those lol - such as the trademark, copyright and other special symbols.
Cheers

**Comment by maciejgryka** [comment] 2016-09-09 13:54
@Vittalev no, you should not report this! While we try to be as specific as possible, there is some common sense we require from you and in this case it's pretty obvious that the "X" icon is the "X" icon. If there was any test next to it, it could be somewhat confusing, but this case is very clear.

**Comment by maciejgryka** [comment] 2016-09-09 13:57
@kwimy this should be reported because there's no other way for us to make the rules consistent. The environment says more than just `(default)` and the test author should specify this. With just `(default)` the step would also pass if the `(default)` was next to the wrong environment (the "right" environment might be obvious from previous steps, but that's not always the case).

**Comment by maciejgryka** [comment] 2016-09-09 14:10
> Also do place holders also mean OPTIONAL. For instance if "Caught Big Fish_" is used in the instructions but on the page there is onyl Caught Big Fish but nothing that follows, we can pass this as well correct ?

@JPierreS yes, you can pass this, unless the test description says something specific about what the placeholder should be.

About special characters, I feel like you're trying too hard to come up with weird scenarios :) There's no way for me to tell you exactly what to do when you encounter each potentilly-un-typeable character, this is again a situation where you have to use your own judgement. We try to be as consistent as possible, but can't always predict what our clients will try to do. If in doubt, it's always safer to answer "No".

**Comment by maciejgryka** [comment] 2016-09-09 14:11
Folks, I'm closing this. I hope I managed to answer your most pressing questions, but I have to focus on doing other things that will benefit us and all of you more. Happy testing! ❤️

**Closed by maciejgryka** 2016-09-09 14:11 UTC
