### ISSUE TITLE
application error

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#235] opened 2016-06-20 11:54 UTC
app error in the web page. i look https://status.rainforestqa.com/  ping 200+

**Comment by shrestha15207** [comment] 2016-06-20 11:58
one more bad start on Monday even its said new virtual machines has been added.

**Comment by JrRandy** [comment] 2016-06-20 11:58
Also had some issues even turning on the extension this morning.  Had bad lag flipping on.

Rumor has it, today was the day they were installing some new servers to help alleviate the VM issues we have seen, so perhaps its the install/updates etc that is going on sucking up the bandwidth.  Heres hoping anyways!

**Comment by GreekGuy** [comment] 2016-06-20 12:00
I get no virtual machines and erros i have done 3 tests in 4 hours

**Comment by uangonline** [comment] 2016-06-20 12:04
Yap, it's seems every monday this kind of error appear more than other days.

**Comment by uangonline** [comment] 2016-06-20 12:07
And also the connection is very slow.

**Comment by zfonck123** [comment] 2016-06-20 12:07
yes very slow, ping 224 ms u.U

**Comment by uangonline** [comment] 2016-06-20 12:07
Maybe the rainforestqa team just hate monday. lol

**Comment by uangonline** [comment] 2016-06-20 12:10
What i don't understand is, when i tried to ping tester.rainforestqa.com i got average 20 ms, which is should be good. So i don't know ehere the lag come from.

**Comment by zfonck123** [comment] 2016-06-20 12:12
https://status.rainforestqa.com/ check it

**Comment by uangonline** [comment] 2016-06-20 12:14
Yes in status page it said response time is above 200 ms, but when i tried to ping it my self it only give me about 20 ms. So i think the problem is not with the network it self, but with the VM machine.

**Comment by shrestha15207** [comment] 2016-06-20 12:32
it seems response time is back to normal but 'There are no virtual machines currently available.' is everywhere

**Comment by zfonck123** [comment] 2016-06-20 12:33
3 jobs in blank page -_-

**Comment by hunt40** [comment] 2016-06-20 12:39
why this no virtual machines or any work because Grinch stole all the servers

**Comment by uangonline** [comment] 2016-06-20 12:45
@shrestha15207 Yap, i think the team have to shut down some server to preserve power on saturday and sunday. And because of there is time different between a lot of us and the company, so when we already monday they still sunday.

**Comment by suplazam** [comment] 2016-06-20 13:01
Application Error and There are no VM's

**Comment by zfonck123** [comment] 2016-06-20 15:28
again same error

**Comment by hunt40** [comment] 2016-06-20 15:32
yeah my stomach ulser coming back thank to rf,first something went wrong or application error then no vm,brilliant company,they will be out of business but they outsourced their test to crowdsourcing platform so they pay much much lower then pay internal testing team so thats why they are in still business.

**Comment by marius11** [comment] 2016-06-20 16:47
@hunt40 Wow... You should probably take a look here: https://www.rainforestqa.com/jobs/. You won't get any error messages (unless you write code) if you successfully get "assigned" on of their positions.

The folks at Rainforest are most likely aware of this and trying their best to make it easier for us.

**Comment by zfonck123** [comment] 2016-06-20 16:58
app error again

**Comment by zfonck123** [comment] 2016-06-20 16:59
![image](https://cloud.githubusercontent.com/assets/19192312/16203130/90259540-36e2-11e6-9f6b-649459ae8fc6.png)

**Comment by shrestha15207** [comment] 2016-06-20 17:00
AND THIS "We're sorry, we've reached the maximum number of concurrent testers we can support. Please reload and try again."

**Comment by MarinaCec** [comment] 2016-06-20 17:21
it is overcrowded, they ruined rainforest

**Comment by zfonck123** [comment] 2016-06-20 17:32
new servers... and alots error of application error today. what happen ???

**Comment by nerdatwork** [comment] 2016-06-20 17:42
Every new approach is filled with drawbacks too its our job to be patient and help them in every possible way. Rainforest is aware of the things that are not working and how things should work. Adding to their frustration with threads that purely reflect negativity isnt going to help things move forward in a positive way. As recently been said, 100 new testers are being added daily. Its obvious they have their hands full and are tirelessly working to get a solution that fixes these issues.

Its easy to point out the errors but its even more tiring and hard to find the exact reason as to why it is causing that error to happen in first place since adding servers should technically fix matters. Not to mention there **could be** testers that are trying ways to get more jobs locked to them in some way that Rainforest is not aware of. 

I am disheartened personally that some members here only speak of what is NOT working, why they  hate to get NO jobs etc etc. This is clearly my personal opinion, nobody forced anyone to do Rainforest jobs, nobody threatened to delete your accounts on your Neobux/Clixsense websites if you didnt work on Rainforest jobs then why "rant".

**Comment by zfonck123** [comment] 2016-06-20 17:51
I think you should take a desicion on new users and old users. I think there must be another method by which send jobs (links ) for older workers with a full amount of work 1500-2000 or higher. many people rely on this to take me over. regretfully I understand the need for new users. but also affecting the tester that is dedicated approximately 16 hours every day to carry out the work . and each day is reduced more , or full of errors .

**Comment by nerdatwork** [comment] 2016-06-20 17:57
@zfonck123 Rainforest is working on new structure where the tester that is online for the longest will get jobs first.

**Comment by nerdatwork** [comment] 2016-06-20 18:20
@zfonck123 Since this isnt an issue which has never been covered, I request you to please close this thread.

**Comment by uangonline** [comment] 2016-06-20 18:21
@nerdatwork Couldn't agree more with you. That's why me and my brother (who also a tester for RF) do some simple experiment. Hope tomorrow we have some result of the suspect of what make RF a bit lag.

**Closed** 2016-06-20 18:29 UTC
