### ISSUE TITLE
Job Loss for this error

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#196] opened 2016-05-24 16:08 UTC
![image](https://cloud.githubusercontent.com/assets/19192312/15511113/01b3863a-21a4-11e6-9ce8-59cd2cf39110.png)

how many people loss alot job for this error ?

**Comment by zfonck123** [comment] 2016-05-24 16:09
![image](https://cloud.githubusercontent.com/assets/19192312/15511136/1ed6cba0-21a4-11e6-9bea-4952ae45a616.png)

**Comment by ahmedofhell** [comment] 2016-05-24 16:16
Same here 
This message appears all the time "We're sorry, we've reached the maximum number of concurrent testers we can support. Please reload and try again."

**Comment by Hanifmamun** [comment] 2016-05-24 16:19
Just now I lost one.

**Comment by androwg** [comment] 2016-05-24 16:23
ya this message appears a lot recently and it can consume all of your 5 refresh without going away 
i think there is a problem

**Comment by pscohn** [comment] 2016-05-24 16:26
We're working to improve our vm capacity. Closing as a duplicate of https://github.com/rainforestapp/tester-chrome-extension/issues/191

**Closed by pscohn** 2016-05-24 16:26 UTC
