### ISSUE TITLE
unable to claim profile 

### ISSUE THREAD

**Issue by josejecr97** [rainforestapp/tester-chrome-extension#299] opened 2016-07-06 18:42 UTC
i have two friends that wants to test web app.. but when they tried to claim profile they dont get any notification back .. can pls help them?..

their contribuitor id are : 38560198 
and 38593155 .

thanks.

**Comment by luisdanielvc** [comment] 2016-07-06 19:16
This is the same as #246 but nobody answers there, i have a friend with ID number 38418874 in the same situation.

**Comment by josejecr97** [comment] 2016-07-06 21:07
@pscohn

**Comment by pscohn** [comment] 2016-07-06 21:11
@josejecr97 I checked both of these ids and we don't have a record of them in our system. Have they both completed the starter job using those IDs?

**Comment by josejecr97** [comment] 2016-07-06 21:49
@pscohn yes, and they are unable to do the job again .... even using another plataform ... the job is in their job list

**Comment by persman** [comment] 2016-07-07 13:10
@pscohn hi, I have the same problem. I did  "Test Applications For Rainforest Qa", there was just a box and instruction, I read your instruction completely then I checked the box and submitted the job. but I didn't receive any notification. this is my crowdflower ID: 36563074  
please help me. I attached my job history too. 
thanks
![pic](https://cloud.githubusercontent.com/assets/20339005/16654164/c1af9a0c-4411-11e6-99de-d75c0de2f539.png)

**Comment by josejecr97** [comment] 2016-07-07 13:28
yes... same here .. 

pls help us.. is there anyway to take another ID in cf? restart the job or something? i think is bugged ......  :( sad

![restart](https://cloud.githubusercontent.com/assets/17110228/16654623/a1075426-4424-11e6-9587-8b79e61451de.png)

**Comment by persman** [comment] 2016-07-07 18:37
@pscohn  please help us. 
thanks

**Comment by Josephapq** [comment] 2016-07-07 23:33
Same here for my brother:
Worker ID: 38585414

![job history](https://cloud.githubusercontent.com/assets/16495666/16673076/e4a45536-4478-11e6-82d1-acea1e0f054f.jpg)

@pscohn Please help to my brother.

This problem is happening to several people.
Thanks

**Comment by loverrr** [comment] 2016-07-08 11:02
hello 
I have same problem. please fix it. my ID is 38604955.

**Comment by loverrr** [comment] 2016-07-08 11:13
@pscohn

**Comment by Psychodelicc** [comment] 2016-07-08 16:34
I have the same problem my id 38616501

**Comment by jombere** [comment] 2016-07-08 17:03
![a](https://cloud.githubusercontent.com/assets/15624230/16695132/f67bbf22-450b-11e6-911d-7059638b99cc.jpg)
![screenshot_1sss](https://cloud.githubusercontent.com/assets/15624230/16695133/f6a22a36-450b-11e6-9da6-7c7a7be27cf8.jpg)

send work and I do not get any notice, my id is 38616673 contributor, I'd really like to solve this little problem to enter the rainforest.

**Comment by pscohn** [comment] 2016-07-08 17:04
It looks like we've found a problem on our end with creating new testers, I'll update here when we have a fix in place.

**Comment by shosti** [comment] 2016-07-08 17:04
We found the root cause, it should be fixed shortly (within a few hours). Once it's fixed we'll open a new (identical) job on CrowdFlower that you should be able to complete correctly.

**Comment by persman** [comment] 2016-07-08 17:04
thank you very much :D

**Comment by josejecr97** [comment] 2016-07-08 17:10
THANKS!

**Comment by jombere** [comment] 2016-07-08 17:15
ty <3.

**Closed** 2016-07-08 17:18 UTC

**Comment by jombere** [comment] 2016-07-08 17:36
Okay, one last question, which we had already sent the job, we have to get a new corwdflower account? because if so...

**Comment by shosti** [comment] 2016-07-08 17:42
@jombere no, you won't need a new CrowdFlower account. We'll open a new CrowdFlower job and you can use it using your existing CrowdFlower account (but only if your previous attempt didn't get processed properly).

**Comment by jombere** [comment] 2016-07-08 17:43
many thanks. @shosti  <3.<3

**Comment by persman** [comment] 2016-07-08 17:46
thank you, please tell us the ID or the name of the job when you lunch it. thank you again.

**Comment by shosti** [comment] 2016-07-08 18:41
The job has been published (ID 930309, name is unchanged).

**Comment by jombere** [comment] 2016-07-08 21:34
Good, I again arose another question, what if new people want to enter the rf? They use the id antigui work? or how do they?
@shosti @pscohn

**Comment by pscohn** [comment] 2016-07-08 21:52
New testers can do the Rainforest job published on CrowdFlower to get set up with an RF profile. @jombere

**Comment by ruben767** [comment] 2016-07-09 14:33
Seems like this new ID has the same issue, my cousin did it yesterday and he haven't received any notification on his CF notifications index.

**Comment by KurtCobain82** [comment] 2016-07-15 15:36
I have the same problem, i do twice and nothing notification.. Look.
![rainforest test](https://cloud.githubusercontent.com/assets/20479049/16879816/4de89392-4a80-11e6-9e7c-8ce3d055fd10.jpg)
