### ISSUE TITLE
There are no virtual machines currently available. Please retry in a few minutes.

### ISSUE THREAD

**Issue by yoges9** [rainforestapp/tester-chrome-extension#322] opened 2016-07-14 15:20 UTC
i am ready to do jobs, but since 2 days every time getting first There are no virtual machines currently available. Please retry in a few minutes and after that another worker accept the job , this is not a fair system , i have done more than 1600 jobs for rainforestqa, and its very frustating to wait a whole 24 hours and then recieving these messages. plz respect testers if you are  are providing money they are providing you support and 24 hours work, even i love rainforestqa that i can do work for them without money for a week oe in emergency a month even, but its very frustating when you try many times and still not got any jobs . plz change this system , we are with you and will be with you and wish for success to rainforestqa

**Comment by JrRandy** [comment] 2016-07-14 15:28
They are working on an updated system.  This is annoying, but not a bug as it is an expected message when the system runs out of virtual servers.  Please look through the closed threads, and you will see many instances of this same report.  Please close this thread so we do not distract from true issues in the system.

**Closed** 2016-07-14 20:27 UTC
