### ISSUE TITLE
Slow server and failed to take screenshot error

### ISSUE THREAD

**Issue by ahmedofhell** [rainforestapp/tester-chrome-extension#145] opened 2016-04-12 17:46 UTC
The server is pretty slow and takes screenshot also very slow.
Failed to take screenshot error appear most of the time after it "Yes,No,Other" buttons disabled totally and had to return once again from the beginning.

Is anyone facing these problems Or I'm the only one?

**Comment by BonesKnows** [comment] 2016-04-12 18:58
very slow for me to

**Comment by Hanifmamun** [comment] 2016-04-13 00:29
Faced same issue

**Comment by taoufik508** [comment] 2016-04-15 10:53
yes, also for me in so many times

**Comment by pscohn** [comment] 2016-05-19 16:25
Duplicate of https://github.com/rainforestapp/tester-chrome-extension/issues/7

**Closed by pscohn** 2016-05-19 16:25 UTC
