### ISSUE TITLE
Too many oops messages

### ISSUE THREAD

**Issue by khristianjose** [rainforestapp/tester-chrome-extension#104] opened 2016-02-29 18:43 UTC
Ive getting too many oops messages since today, i get some like 5 job per day and now im getting like two cuz the other 3 are oops, theres a link with oops

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx4fee59-512b-47c0-8ca2-b5ff0afa4b9c&browser=any&hitId=4286446&sig=20a216718fb9bd59d4230d1159c58c8bbeeb916a04553b009b1f1baa2532b919&turkSubmitTo=%2Fthanks&workerId=33833144

**Comment by khristianjose** [comment] 2016-02-29 18:44
Another oopps 

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxa05bf8-bcc7-43f5-b659-350c372ec76a&browser=any&hitId=4286446&sig=d9aab6277d85d52efb52d5c675e17238d861bbe71a61ceb4e5792c4525a6741e&turkSubmitTo=%2Fthanks&workerId=33833144

**Comment by khristianjose** [comment] 2016-02-29 18:48
And another 

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx8262f1-83ec-43bd-80c9-0cac9330c2bd&browser=any&hitId=4286446&sig=9f9c2f9988284d403bb632ceceec48e59d2c7e056c12a2fc84bfbabed372bb16&turkSubmitTo=%2Fthanks&workerId=33833144

**Comment by khristianjose** [comment] 2016-02-29 18:50
4 in a row im sorry if im creating too many comments.

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx4af07a-cf95-4522-865d-ed0258e441cb&browser=any&hitId=4286446&sig=24eefdfe64ddf9ad0e37c005a1d42499b382cbd564e3eaa5347eb8e01b5f16b5&turkSubmitTo=%2Fthanks&workerId=33833144

**Comment by helloworld111gh** [comment] 2016-02-29 18:51
Oops messages are expected and not a bug.

**Comment by khristianjose** [comment] 2016-02-29 18:52
i saw this on another post and one admin was requesting the links, i dont know.

**Comment by marius11** [comment] 2016-02-29 21:15
@helloworld111gh These oopses transformed into server errors. I averaged one hit every 15 seconds in the last three hours and 99% of them have been server errors/application errors.

**Comment by masterpeing** [comment] 2016-02-29 22:10
Ooops: another worker accepted the job before you! It doesn't look like there is any more work for any of our hits; please try again shortly - you can refresh this page, or return this hit.

today i recibe like 20 jobs and all said oops... well really this is getting really annoying . . is kinda spamming useless invitations :/

**Comment by Deepak0988** [comment] 2016-03-01 02:38
Same Issue Iam facing... Looks like after recent update of extension I got only 1 hit to complete. Every time some update happens and there issue arise.

**Comment by nerdatwork** [comment] 2016-03-01 05:15
Its already covered in #22 please check the earlier posts so Rainforest staff can better address the issue at hand. Duplicate posts will not speed up the process of fixing bugs. Thank you.

**Comment by manishflyboy** [comment] 2016-03-01 11:44
From last two days getting too many oops massages.

**Comment by pscohn** [comment] 2016-03-01 15:08
@nerdatwork and @helloworld111gh are correct, plus we have enough links, so closing :)

**Closed by pscohn** 2016-03-01 15:08 UTC
