### ISSUE TITLE
I sent the work from CrowdFlower and I do not get any notification.

### ISSUE THREAD

**Issue by jombere** [rainforestapp/tester-chrome-extension#306] opened 2016-07-08 16:46 UTC
send work and I do not get any notice, my id is 38616673 contributor, I'd really like to solve this little problem to enter the rainforest.
:(
![a](https://cloud.githubusercontent.com/assets/15624230/16694713/c36d3fcc-4509-11e6-8803-c9ca8a3ab853.jpg)

![screenshot_1sss](https://cloud.githubusercontent.com/assets/15624230/16694714/c377c9ec-4509-11e6-99d7-be93fc1e9e48.jpg)

@pscohn

**Comment by persman** [comment] 2016-07-08 16:56
hi 
we all have the same problem 
you can check it here:
https://github.com/rainforestapp/tester-chrome-extension/issues/299
I hope that @pscohn solves this problem

**Comment by josejecr97** [comment] 2016-07-08 16:59
we're many with the same problem... check #299

**Comment by pscohn** [comment] 2016-07-08 17:03
Duplicate of https://github.com/rainforestapp/tester-chrome-extension/issues/299

**Closed by pscohn** 2016-07-08 17:03 UTC
