### ISSUE TITLE
You have reached the maximum number of unsubmitted assignments. So we are fair to other workers, we stop you doing too much for us at once. You can complete the other assignment(s) and refresh this page, or simply return this hit.

### ISSUE THREAD

**Issue by markoobrez** [rainforestapp/tester-chrome-extension#18] opened 2015-11-24 23:13 UTC
since friday i do 3 task 
when i open task everytime write You have reached the maximum number of unsubmitted assignments. So we are fair to other workers, we stop you doing too much for us at once. You can complete the other assignment(s) and refresh this page, or simply return this hit.
please fix it

**Comment by ukd1** [comment] 2015-11-25 00:59
closing as this is a duplicate of #17

**Closed by ukd1** 2015-11-25 00:59 UTC
