### ISSUE TITLE
Error: Something wrong

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#167] opened 2016-05-04 22:47 UTC
![image](https://cloud.githubusercontent.com/assets/19192312/15031678/51f6edc4-1224-11e6-959e-f2642fff9232.png)
  this time alot ,and later  affter reaload 
![image](https://cloud.githubusercontent.com/assets/19192312/15031699/717a87fa-1224-11e6-8a3c-fb257a29f651.png)

**Comment by RezwanulHaque** [comment] 2016-05-04 22:50
Same thing here also

**Comment by nerdatwork** [comment] 2016-05-19 06:38
This was from 14 days ago so I assume you are not facing this problem anymore. If you are able to work properly and dont have this issue, I kindly urge you to close this thread. If you are still facing the issue please send a support ticket from your Rainforest portal or email them at tester@rainforestqa.com

**Comment by pscohn** [comment] 2016-05-19 16:03
Dupe of https://github.com/rainforestapp/tester-chrome-extension/issues/172

**Closed by pscohn** 2016-05-19 16:03 UTC
