### ISSUE TITLE
Missing hits

### ISSUE THREAD

**Issue by MarinaCec** [rainforestapp/tester-chrome-extension#272] opened 2016-06-30 13:18 UTC
I only got one hit today, is this normal?

**Comment by CassianoTerzi** [comment] 2016-06-30 13:20
Me too, It has been 4 hours since my last hit

**Comment by MarinaCec** [comment] 2016-06-30 13:21
@CassianoTerzi same here, this is so sad :(

**Comment by khristianjose** [comment] 2016-06-30 13:21
Ive started the day like 5 hours ago and i only receive one hit from now, just a bad day immo, or i dont know, this is a bad week for Rainforest, very low jobs for testers.

**Comment by GedocBorges** [comment] 2016-06-30 13:21
Regrettable, almost 6hrs without hits.

**Comment by ilegalna** [comment] 2016-06-30 13:22
Same here :(

**Comment by zfonck123** [comment] 2016-06-30 13:26
same here

**Comment by CassianoTerzi** [comment] 2016-06-30 13:45
And When one Hit appear....
"Error 522 Ray ID: 2bb20cd8659b4c90 • 2016-06-30 13:44:13 UTC
Connection timed out"

**Comment by MarinaCec** [comment] 2016-06-30 14:06
@CassianoTerzi I love to work for rainforest, but unfortunately I think q they are not caring about the dissatisfaction of testers, every day comes more testers and work/site get worse, and comes less tests pro older members

**Comment by CassianoTerzi** [comment] 2016-06-30 14:10
@MarinaCec I totaly agree with you

**Comment by tulko** [comment] 2016-06-30 14:11
more testers who can support your system. A test requires some concentration. I can not do anything when I do a test, I can not spend hours and hours waiting for a test. This is sad. Neobux forum I see very happy new testers for its 10 dollars a day.

**Comment by MarinaCec** [comment] 2016-06-30 14:30
@tulko good point, I'm getting less than 3 dollars a day, this is very sad, doesn't worth it

**Comment by qpPykT** [comment] 2016-06-30 14:49
@MarinaCec 
If you do well enough with English. Take a look on usability testing. On the Internet there are a lot of projects with that type of testing.

**Comment by MarinaCec** [comment] 2016-06-30 15:22
@qpPykT Do you know any site that uses testers like the rainforest?

**Comment by tulko** [comment] 2016-06-30 15:29
there are many tasks. the problem is that indiscriminately increase the amount of tester. They have a random system that benefits few. They tell you if you try you can make 100 test, so we give you the bonus. But there is nothing you can do to get to do 100 tests in one day. You just need to be lucky. They say they are working on a new allocation system works. But until the momenton or there was news. But meanwhile hurting accepting new testers who have spent some time in supporting and providing RF.
I see that the staff are nice people. I like to see it grow rainforest, and I'm proud to be part of the project. It makes me sad that this growth does not benefit me.

**Comment by pscohn** [comment] 2016-06-30 15:30
I'm going to bring this up to the team and see if we can do something quickly to benefit the testers that have been around longer.

**Comment by Yhenko** [comment] 2016-06-30 16:10
im frustrated, VM's errors and other workers accepts the hit :(

**Comment by ilegalna** [comment] 2016-06-30 16:35
Thank you @pscohn :+1:

**Comment by MarinaCec** [comment] 2016-06-30 16:44
@pscohn ok, thanks :+1:

**Comment by federicoall** [comment] 2016-06-30 17:04
@pscohn thank you bro

**Comment by vladfuller** [comment] 2016-06-30 17:15
Please bro.... I know you are acepting new testers to the system, but i think u need to do something special for testers are with u since 6 month ago or 1 year ago and testers already did more than 2000 hits... it will be great

**Comment by MarinaCec** [comment] 2016-06-30 17:29
I think they should have a little consideration at least with regular testers like us, I'm testing 5/7 days a week for more than 8 months, I'm kind 16hours/day active

**Comment by huynhxuanvinh** [comment] 2016-07-01 05:13
I can't understand old members have complaint for what? They have joined early for months or for years, do many jobs (many people show above 2000 jobs). At their time, they have 30-50 hits per day to test (8-20 $ per day). Some of them have passed 1000$ until today and now they start complaining about the number of hits they get. Do you know a new member has only 1 or 3 or 5 hit per day. This job is kind easy, only require doing it carefully so you can't say old member has more "experience" than new members., new member can learn and do it perfectly after some days testing it. I respect your desire but I think the number of hit should be distributed fairly for ALL members. Even though in that case, the old testers still have many benefits than the new ones.

**Comment by mobradovic** [comment] 2016-07-01 06:58
> number of hit should be distributed fairly for ALL  members

Totally agree.

**Comment by olikengr** [comment] 2016-07-01 14:32
Same here, less jobs for old testers...

**Comment by samballode6** [comment] 2016-07-02 13:54
Same here

**Comment by mikeb79** [comment] 2016-07-02 18:30
Same to me :(

**Comment by nagabhyru** [comment] 2016-07-05 05:44
Same here. Getting some couple of jobs but they are ending up with either "No VM's" or "Another worker". Waiting for hours for couple of jobs that hardly earns $1 or $2 is not worthy.

Like crowdflower, RF should have levels (Level-1, Level-2 and Level-3) and accuracy rate. It will help the members to assess the quality of work they are doing and each one get there share of work.

**Comment by ilegalna** [comment] 2016-07-05 11:26
Another worker.... all day :(

**Comment by nagabhyru** [comment] 2016-07-05 13:18
Again "Another worker". "No VMS" all the day.

**Comment by MarinaCec** [comment] 2016-07-05 13:35
@nagabhyru "Like crowdflower, RF should have levels (Level-1, Level-2 and Level-3) and accuracy rate. It will help the members to assess the quality of work they are doing and each one get there share of work."

it sounds good

**Comment by samballode6** [comment] 2016-07-05 14:29
The more day pass, more less jobs received, why is that ?

**Comment by felipeinsanobr** [comment] 2016-07-05 15:46
same here !

**Comment by MarinaCec** [comment] 2016-07-05 15:46
nothing today :(

**Comment by vladfuller** [comment] 2016-07-05 23:52
3 days in a row and got only 5 hits

**Comment by mikeb79** [comment] 2016-07-06 01:18
Got 1 today but took me out "lost connection", could not get it back :/

**Comment by huynhxuanvinh** [comment] 2016-07-06 02:33
yesterday is dried for me but today I got 10 hits on the first 2 hours. Hope can reach 40 hits today. Very happy.

**Comment by mikeb79** [comment] 2016-07-06 02:40
Got 3 since my last comment. (y)

**Comment by nagabhyru** [comment] 2016-07-06 13:41
Today also same. Some jobs didn't open at all. Some open end up with "No VM's" followed by "Another worker". I think it time to move on :(

**Comment by MarinaCec** [comment] 2016-07-06 17:34
@nagabhyru same here, had to report on the first step the few that came

**Comment by srsaurabh32** [comment] 2016-07-10 16:33
only did two hits in the whoooole day.......don't know why?

**Comment by marius11** [comment] 2016-07-10 17:24
@srsaurabh32 Because it's the weekend, more specifically, Sunday?

**Comment by srsaurabh32** [comment] 2016-07-10 19:57
@marius11 is it? Fine but i have one more issue did you see the issue I have listed on top : Unknown error? please look at the screen shots and please revert back, have you seen this before.

**Comment by JrRandy** [comment] 2016-07-14 00:56
Not sure if this issue is still happening to some of you, but if not please close this thread so we can keep active issues being addressed.

**Comment by MarinaCec** [comment] 2016-07-15 13:11
@JrRandy YES still happening, had no tests today

**Closed** 2016-10-16 16:59 UTC
