### ISSUE TITLE
extension not working

### ISSUE THREAD

**Issue by MuhammadRafique182014** [rainforestapp/tester-chrome-extension#6] opened 2015-11-04 08:47 UTC
mine extension is not working its always saying no ,
don't know why but it worked on yesterday, again I have to check task list to catch hits

**Comment by MuhammadRafique182014** [comment] 2015-11-04 09:19
Its working now lol

**Comment by ukd1** [comment] 2015-11-05 19:42
@MuhammadRafique182014 can you give me your worker id, so I can investigate why? Are you getting work from outside of here?

**Comment by MuhammadRafique182014** [comment] 2015-11-06 08:20
32706681

**Comment by MuhammadRafique182014** [comment] 2015-11-07 18:30
again its not working

**Comment by MuhammadRafique182014** [comment] 2015-11-16 19:12
again not working WTH happened to the extension no use of it 
my worker ID 32706681

**Comment by ukd1** [comment] 2015-11-16 19:21
Thanks - what error are you seeing?

**Comment by androwg** [comment] 2015-11-16 21:14
@ukd1 can u tell us where we can see if there is an error? so we can help you

**Comment by KabakF** [comment] 2015-11-16 23:00
@ukd1  @helloworld111gh We'd  be really glad if you fix this Russ. There is no error shown. Extension is not really working for us
(if it would help, My Worker ID: 31122298 )

**Comment by pscohn** [comment] 2015-11-17 17:53
Closed as duplicate of https://github.com/rainforestapp/tester-chrome-extension/issues/11

**Closed by pscohn** 2015-11-17 17:53 UTC
