### ISSUE TITLE
test not payment

### ISSUE THREAD

**Issue by awnosa** [rainforestapp/tester-chrome-extension#30] opened 2015-12-17 15:21 UTC
this test not paid and I'm finished this task to the end without any problem, this is url of task

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx1053c7-b4ef-443a-81b5-b0fcdccff033&browser=any&hitId=4622631&sig=6d5e58d3ce23cb9749f3a2f3317250034ceeaef83f8a427f803fb57b22f404e3&turkSubmitTo=%2Fthanks&workerId=32656569

11 steps

my ID 32656569

this is url of failed test not paid

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx6a2d94-26f4-48e1-915e-1764a37ef434&browser=any&hitId=4622425&sig=60c5e7ccbd753d7954dc0ed455c703b9481641a9abeadd59bafd13159bb0598e&turkSubmitTo=%2Fthanks&workerId=32656569#

17 steps

![2](https://cloud.githubusercontent.com/assets/16338438/11873312/b6f77e7c-a48e-11e5-9d4b-3f292cc5a847.png)

![default](https://cloud.githubusercontent.com/assets/16338438/11873316/ba10b984-a48e-11e5-8968-ee26278ca2b7.png)

**Comment by pscohn** [comment] 2015-12-17 16:28
Closing as duplicate of https://github.com/rainforestapp/tester-chrome-extension/issues/27, you may repost there.

**Closed by pscohn** 2015-12-17 16:28 UTC
