### ISSUE TITLE
 is impossible to work , this is the second day with the same problem

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#612] opened 2016-09-22 16:12 UTC
![image](https://cloud.githubusercontent.com/assets/19192312/18756396/cc344962-80bd-11e6-807a-7b323e38fa19.png)

is impossible to work , this is the second day with the same problem

**Comment by zfonck123** [comment] 2016-09-22 16:27
and not is only the work, the web page  too  https://status.rainforestqa.com/  ,http://rainforestqa.com/,, alot time for loading https://portal.rainforestqa.com/... DNS ? INTERNET ? :(

**Comment by JrRandy** [comment] 2016-09-22 18:23
Do a tracert to rainforestqa.com  I am not seeing any issues with connectivity, so depending on your location it might be an undersea connection or something.

**Comment by zfonck123** [comment] 2016-09-22 18:29
not is my connection...

**Comment by JrRandy** [comment] 2016-09-22 18:31
Im not sure what you mean by "Not is my connection"

**Comment by zfonck123** [comment] 2016-09-22 18:42
because i can watching hd movies with my internet in this moment, but cant loading one terminal :/ i hate this problem... losss more of 10 hit... my friends have a same problem too

**Comment by uqbiii** [comment] 2016-09-22 18:44
Everything is working fine, Today is a busy day and completed 25+ but not a single time any thing like mentioned above happened to me.

**Comment by JrRandy** [comment] 2016-09-22 18:46
That has nothing to do with anything.  I never stated it was your connection, I stated that it may be an issue with an undersea connection or something along those lines.  Rainforest is hosted within CloudFlare, and CloudFlare is located in San Francisco California.  Unless you are attempting to use something else in this exact same location, you are comparing apples to oranges.  My servers load quickly, and I have a 35ms connection to the CloudFlare hosting center.  You are likely taking a different path to get to the same place due to your location, and you may be taking an inefficient path due to an outage somewhere, or hitting a connection or device that is over utilized and creating latency as it passes that connection.

**Comment by NICOSYSTEM3** [comment] 2016-09-22 19:11
![image](https://cloud.githubusercontent.com/assets/22378777/18762431/b8840b46-80d6-11e6-8b02-dec6616a9521.png)

This is normal? connection fails? All day with the same case. I could not work :(

**Comment by JrRandy** [comment] 2016-09-22 19:13
Normal?  No.  Affecting everyone?  No.  Can you perform a tracert to tester.rainforestqa.com?

**Comment by NICOSYSTEM3** [comment] 2016-09-22 19:17
JrRandy Please, explain what the tracert. As is done? I do not know what he's talking about

**Comment by zfonck123** [comment] 2016-09-22 19:17
can explaim how do a tracert  please ? thx

**Comment by JrRandy** [comment] 2016-09-22 19:21
Open a command prompt (Assuming windows, start -> Run -> type "cmd" without the quotes and press enter).  A black window should open.  Type:  "tracert tester.rainforestqa.com" without the quotes, and press enter.  You should see a series of lines with numbers and perhaps words.  Wait until it states "Trace Complete" then screenshot and post.

**Comment by zfonck123** [comment] 2016-09-22 19:28
![image](https://cloud.githubusercontent.com/assets/19192312/18762934/27288c64-80d9-11e6-9cc0-64725dbb10e2.png)

**Comment by NICOSYSTEM3** [comment] 2016-09-22 19:31
zfonck123 como le haces? eres venezolano verdad? a mi me da error

**Comment by JrRandy** [comment] 2016-09-22 19:36
That tracert doesnt look too bad at all, certainly should not be causing any major issues (unless that * on hop 10 is consistent drops as opposed to an anomaly).  Anyone know if the terminals are located somewhere else behind the scenes?

**Comment by NICOSYSTEM3** [comment] 2016-09-22 19:36
![image](https://cloud.githubusercontent.com/assets/22378777/18763227/61ad78f8-80da-11e6-8e17-2fcab7e2a43b.png)

este es el mio

**Comment by JrRandy** [comment] 2016-09-22 19:39
hmmm, looks like @NICOSYSTEM3 takes a very similar path and has a timeout on 179.1.7.22 as well.  Looks like there may be an issue in the transition from Latin America to the US causing packet loss.

**Comment by CharlieSpock** [comment] 2016-09-22 19:41
If you are located in Venezuela. CANTV servers make problems with NB and RF

**Comment by RnkSts** [comment] 2016-09-22 19:43
Well I just disable the extension for now. Hits end in a blank page (after load) and can't do nothing for the moment.
![screenshot_3](https://cloud.githubusercontent.com/assets/20311303/18763368/1090d57c-80db-11e6-9f6c-b2c14b0de46b.png)

**Comment by zfonck123** [comment] 2016-09-22 19:45
and this problem start yesterday  in the night

**Comment by JrRandy** [comment] 2016-09-22 19:49
Wonder if anyone in Latin America is not experiencing issues lol

**Comment by uqbiii** [comment] 2016-09-22 19:49
Not facing the problem, here's mine, may it helps to understand the problem.
![](http://image.prntscr.com/image/3a50eb096fc74cd59a0eba0e2e1df5f7.png)
Here is a link which may help you, i don't know it's 100% correct or not but it found some errors so i thought to share it with you.
http://dnscheck.pingdom.com/?domain=rainforestqa.com&timestamp=1474573685&view=1

**Comment by marius11** [comment] 2016-09-22 19:52
I'm having the same problem as @NICOSYSTEM3. No wonder I haven't received any assignments this week.

**Comment by RnkSts** [comment] 2016-09-22 20:07
So this is the problem, mmm... Any suggestions?
![screenshot_5](https://cloud.githubusercontent.com/assets/20311303/18764249/8c0d435e-80de-11e6-865f-baf89cc2d575.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/20311303/18764250/8c1454c8-80de-11e6-9ab6-e6f6a59de32b.png)

**Comment by zfonck123** [comment] 2016-09-22 20:07
same too

**Comment by JrRandy** [comment] 2016-09-22 20:08
Im not sure that is the problem @RnkSts.  I see the same, and am having no issues like you guys are.  So far, everyone having problems is coming out of Latin America, so it is more likely an issue between LatAm and USA than it is some DNSSEC settings.

**Comment by marius11** [comment] 2016-09-22 20:19
@JrRandy I'm not from Latin America, yet I'm having the same problem.

**Comment by JrRandy** [comment] 2016-09-22 20:20
@marius11 Whats your tracert look like?

**Comment by RnkSts** [comment] 2016-09-22 20:27
@JrRandy You may be right, and this maybe is a problem of connection between the US and LatAm, but I also find it strange that the only pages that give me problems are only the jobs, all the other sites from rainforest work properly.

This is how my hits looks like:
![screenshot_7](https://cloud.githubusercontent.com/assets/20311303/18764734/ce618de4-80e0-11e6-8206-ac0afd912c30.png)

Better I keep the extension OFF and leave the jobs to those who can complete them, hopping we can continue working ASAP.

**Comment by marius11** [comment] 2016-09-22 20:28
![tmp](https://cloud.githubusercontent.com/assets/11650839/18764921/2d695070-811c-11e6-8e2a-f5eb47224dfa.png)

**Comment by JrRandy** [comment] 2016-09-22 20:32
@marius11 You have a whole different issue.  That is way too many lost packets for a tracert.  You are only hitting 1/3 on almost every hop once you leave your internal network.  You are going to expeirence a world of issues.

**Comment by WillVM** [comment] 2016-09-22 22:25
1    <1 ms    <1 ms    <1 ms  192.168.0.1
  2    15 ms    15 ms    16 ms  172.17.1.247
  3    15 ms    15 ms    15 ms  172.16.26.65
  4    19 ms    18 ms    18 ms  10.150.0.105
  5    16 ms    19 ms    19 ms  10.150.0.90
  6    15 ms    15 ms    16 ms  10.150.0.230
  7    18 ms    16 ms    16 ms  200.61.252.2
  8    17 ms    16 ms    16 ms  200.61.252.5
  9     *        *       63 ms  179.1.70.253
 10     *       62 ms    62 ms  179.1.7.22
 11    63 ms     *       61 ms  104.25.172.10

Traza completa.

Same problem here, VM never loads and problems with Neobux page too.

**Comment by kuartx** [comment] 2016-09-22 23:01
1     3 ms    <1 ms    <1 ms  192.168.0.1
  2    48 ms    33 ms    33 ms  anz-05-lo77.bras.cantv.net [190.203.224.1]
  3    34 ms    34 ms    67 ms  172.26.28.65
  4     *        *        *     Tiempo de espera agotado para esta solicitud.
  5    38 ms    37 ms    37 ms  10.82.1.113
  6    39 ms    38 ms    39 ms  10.113.9.45
  7    37 ms    37 ms    37 ms  10.150.0.230
  8    40 ms    38 ms    37 ms  200.61.252.2
  9    38 ms    37 ms    38 ms  200.61.252.5
 10     *        *        *     Tiempo de espera agotado para esta solicitud.
 11    83 ms    82 ms    83 ms  179.1.7.22
 12    82 ms     *       82 ms  104.25.172.10

Traza completa.

Here is mine, same problem me too, please any way to fix it? 2 days with this problem =(

**Comment by zfonck123** [comment] 2016-09-23 00:56
![image](https://cloud.githubusercontent.com/assets/19192312/18770746/0dfb1e40-8107-11e6-96c4-4cb1305e5b34.png)
now this error, and very very slow for loading the pages

**Comment by NICOSYSTEM3** [comment] 2016-09-23 01:07
![image](https://cloud.githubusercontent.com/assets/22378777/18770946/88e4c1f0-8108-11e6-82b5-bdb73f6fabf0.png)

Getting worse, now I get it. After much waiting, the page is so :(

**Comment by zfonck123** [comment] 2016-09-23 01:44
![2c4a531a-810d-11e6-93e8-92068948fbe0](https://cloud.githubusercontent.com/assets/19192312/18771529/ab6bcd4a-810d-11e6-8841-0c8d70f07b46.png)
new problem

**Comment by RnkSts** [comment] 2016-09-23 09:44
Everything seems to be back to normal since several hours ago, if you guys have not problems, you can close this issue.

**Comment by zfonck123** [comment] 2016-09-23 19:06
same problem today

**Comment by RnkSts** [comment] 2016-09-24 01:48
The problem is related to the ISP. If you are in Venezuela (supongo que la mayoría de los que tienen este problema), Cantv is giving intermittent problems (como siempre), and it would be best to wait until these problems are gone. I recommend being active from midnight or early morning hours, when the speed is at its best.
#620 #610

**Comment by mariaelite** [comment] 2016-09-26 03:17
@RnkSts  Not CANTV.
If you like to speculate.
In Argentina, U.S.A., Spain have the same problem multiple users.
This is something else

**Comment by Josephapq** [comment] 2016-09-26 03:28
Best regards

I have 8 people nearby who are going through the same situation.
For several days (this week) it is impossible to carry out a test.
For these people it is frustrating not being able to work because they consider rainforestqa as a source of income important.

I don´t know if the problem is due to the updates that were implemented this week.
But they were working normally. I have done some testing together and we conclude that it is some sort of problem with the DNS or ISP. Similarly I suggested to report this problem with the internet service provider is important that Rainforestqa has be aware of the problem because (I repeat), I do not know if the problem is related to updates made this week.

I appreciate all the help they can lend.

**Comment by omar0711** [comment] 2016-09-26 03:35
same problem @Josephapq

**Comment by mariaelite** [comment] 2016-09-26 03:48
Josephapq   I agree with you.
Here alone can give us an answer to the problem is rainforest.

**Comment by zfonck123** [comment] 2016-09-26 13:26
today same problem... @pscohn @kristen-allie  @sweeneyapps

**Comment by sweeneyapps** [comment] 2016-09-26 15:05
@zfonck123 I wish I could help but I don't work for RainforestQA.   All I can help is to improve the extension on github.    But anyway, you can describe your problem again?   Network problem inside the console?

**Comment by vladfuller** [comment] 2016-09-26 15:09
I have the same problem.... it happened since thursday last week i couldnt load VM past days
![11](https://cloud.githubusercontent.com/assets/17486099/18839647/bcc3f7ba-83d9-11e6-9d55-5bed85b291ec.png)

**Comment by marius11** [comment] 2016-09-26 15:26
You wrote *tester.rainforest.com* instead of *tester.rainforest**qa**.com*.

**Comment by vladfuller** [comment] 2016-09-26 15:31
Oh ur right 
![12](https://cloud.githubusercontent.com/assets/17486099/18840477/bf11d426-83dc-11e6-889b-7b8b7e506e3b.png)

**Comment by sweeneyapps** [comment] 2016-09-26 15:31
btw this command, **ping tester.rainforestqa.com**

would be simpler.

**Comment by zfonck123** [comment] 2016-09-26 15:48
:( i dont know why have this problem, thursday last week, and alot people from my country too :(.  maybe can provide one dns for can open the wep page more fast,  in this moment stucking loading the virtual machine, and take alot time to load any page of rainforest

**Comment by Hodusty** [comment] 2016-09-26 16:36
Same here from the last Friday i having lost of packets and VMs are not loading, Please Rainforest, Take a look to this. Its weird because only happen to this connection, I have change DNS and nothing. I am from Venezuela.

**Comment by ilegalna** [comment] 2016-09-26 19:35
I am not getting any job. Can you please check this, is it ok? My worker ID is 29166275. 

![jas](https://cloud.githubusercontent.com/assets/17131666/18848932/e48f928e-8430-11e6-9bfd-24b570bfce1f.JPG)

I am from the Europe and today I am just receiving - There are no virtual machines currently available. Please retry in a few minutes or Too many requests.

**Comment by JrRandy** [comment] 2016-09-26 20:13
@ilegalna - If you are getting "There are no virtual machines" there is nothing wrong with your account.  The extension is attempting to feed a job, and whatever on the backend that causes these errors occurs.

**Comment by pbwe** [comment] 2016-09-26 22:29
I am from Venezuela, and i'm having the same problem since almost a week ago, the rainforest portal loads (when it loads) extremely but extremely slow (and i know its not something about the connection because any other pages load at the normal speed they alway have, excet for nebux that has exactly the same problem) and the HITs, they open but the page also never loads, it crashes, it says there is a problem with the connection not being private, but i never receive a single hit.

Is this a problem with the internet in Venezuela? Is it Chrome? or is it something the rainforest staff can fix? It's really frustrating not being able to work for almost a week and this keep going....

**Comment by JrRandy** [comment] 2016-09-26 22:39
Considering the number of people from Venezuela that are being affected, and noone else seemingly being affected, I would say that it is an issue with either the Venezuela ISP (I read that CanTV has 80% of the internet customers in Venezuela) or the connectivity from Venezuela to the US.  There is not much anyone on here can do to assist.  One of the posts above say "Argentina, Spain, and USA users have same issue", but this thread has been dominated by people from Venezuela and all tracert's have shown the same path through to the US (179.1.7.22) so I do not know where this information came from as I do not see any evidence to that at all.

**Comment by Hodusty** [comment] 2016-09-26 23:27
I think its something whit the CloudFlare connections neobux its not loading for me either, i dot not its its CANTV again blocking CloudFlare (this happens sometime ago) or CloudFlare platform itself. Jesus this country its killing us. now not even work are going to let us.

**Comment by sweeneyapps** [comment] 2016-09-27 00:06
btw, I'm in California and when I ping 179.1.7.22..  I'm getting 150-200ms response time.    179.1.7.22 is hosted in Colombia by internexa.net.   It appears to be entry point for South America connection to USA.    tester.rainforestqa.com is based in San Francisco.   You can try speedtest.net and try test speed between host in San Francisco and your country to see how good your connection is.   You might ask why other website is loading correctly, it is probably because they have servers all over the globe to ensure better connection such like CDN.   If you felt that it's cloudflare platform then Rainforest can check with them and see what's up.

**Comment by zfonck123** [comment] 2016-09-27 01:03
![image](https://cloud.githubusercontent.com/assets/19192312/18856780/f533904a-842b-11e6-9603-6d915504b3c7.png)  with it i have alot problem i dont know why.

in this 4 day i am use my phone conection for can work... but speent more money for can work T_T 

![image](https://cloud.githubusercontent.com/assets/19192312/18856837/95b3b838-842c-11e6-9df7-761b99a857ae.png)
  with digitel i can work perfect. but spent more money T_T

**Comment by zfonck123** [comment] 2016-09-27 01:05
we need one solution, or anything, i think the 80% of tester from latin american :(

**Comment by RnkSts** [comment] 2016-09-27 02:47
Well guys, now I have not problems to work since 2 days ago, I'm still using Cantv and the connection its slower in the day (I prefer stay active after midnight), And the issues aren't only in Venezuela, so the problem can be anything else, when I had these problems I was able to load another websites fast, but some pages can't load good, like tester.rainforest.com and Facebook.

**Comment by carlosds7** [comment] 2016-09-27 03:09
El problema no es con Rainforest, es por Cantv que esta super lento. @zfonck123

**Comment by zfonck123** [comment] 2016-09-27 11:35
i can load any page very fast, can watching videos hd, but the tester.rainforestqa.com very slow, stuck loading, stuck loading terminal.. T_T

**Comment by JrRandy** [comment] 2016-09-27 12:37
@zfonck123 If your issues exists when you are on CanTV, and does not exist when you are on Digitel, then the issue is with CanTV traffic.  I am not sure what people are expecting to be resolved on this board.  This is NOT a bug with the extension, and that is what this board is for.

**Comment by pbwe** [comment] 2016-09-27 13:11
"i can load any page very fast, can watching videos hd, but the tester.rainforestqa.com very slow, stuck loading, stuck loading terminal.. T_T"
Same, only rainforest, and neobux, there must be something wrong.

**Comment by kristen-allie** [comment] 2016-09-27 15:18
@shosti or @rainforestapp/tester-product what do you think of this? Does it have something to do with the extension, or is it a problem outside of our control? TL;DR VMs aren't loading properly, so some people aren't getting jobs. It might be due to an ISP issue between Latin America and the U.S.

**Comment by shosti** [comment] 2016-09-27 15:31
Definitely not to do with the extension. If it's a connectivity issue (either to the VMs or the main rainforest site) it's likely to be out of our control. @jbarber you have time to look into it really quickly?

**Comment by gallois** [comment] 2016-09-27 15:41
I can't reproduce that. There's no considerable packet loss and the terminals are working fine for me here.

**Closed** 2016-09-27 16:15 UTC

**Comment by jbarber** [comment] 2016-09-27 16:35
traceroute/ping can be filtered/treated specially by carriers, so can be an unreliable test of end-to-end reach-ability and performance.

tester.rainforestqa.com is fronted by a CDN, which uses DNS anycast to point clients to the closest (in terms of network metric) cache of the domain. The terminals are located in Europe so can have a different performance profile to tester.rainforestqa.com via HTTPS. As far as I know, no dynamic content is located in SF.

Other sites (e.g. Google properties such as Youtube, Netflix, LinkedIn, Facebook) might perform adequately due to the presence of local caches within or close to the provider networks.

As far as we know, nothing under our control has changed that would affect network traffic to Latin America or any other region - although it's entirely possible that a BGP peer between the clients and the terminals or our site is overloaded and causing poor network performance.

If you get see a network error in the console such as in [this comment](https://github.com/rainforestapp/tester-chrome-extension/issues/612#issuecomment-249018142), you can try accessing the URL that gives the error, although a connection reset indicates that some host on the route closed the connection. The host that did this is unlikely to be the origin servers, and is much more likely to be an intermediate middle box or router.

**Comment by teckda** [comment] 2016-09-27 16:36
Hi, I'm from Venezuela and all my friends and I have the same problem with loading the VM. Even using different internet providers.

**Comment by Lycanus** [comment] 2016-09-28 16:44
Can I claim multiple profiles to work with the extension with the same account crowflower?

**Comment by kristen-allie** [comment] 2016-09-28 22:26
@Lycanus not at this time. Sorry about that!

**Comment by vladfuller** [comment] 2016-09-29 15:53
Finally i can LOAD VM AGAIN!!!
Thanks God
