### ISSUE TITLE
New users

### ISSUE THREAD

**Issue by ptica-rugalica** [rainforestapp/tester-chrome-extension#29] opened 2015-12-15 11:12 UTC
Hi
Is there any way for new users to start working, because new IDs are not posted on CrowdFlower. Thank You

**Comment by L4kshmi** [comment] 2015-12-15 16:15
I also appreciate the help can provide in this matter

**Comment by pscohn** [comment] 2015-12-17 17:27
This is a duplicate of https://github.com/rainforestapp/tester-chrome-extension/issues/24, see there for more info.

The short answer is it's very difficult for new users to get started right now, but we're going to fix this soon.

**Closed by pscohn** 2015-12-17 17:27 UTC
