### ISSUE TITLE
no work today

### ISSUE THREAD

**Issue by blagoslav** [rainforestapp/tester-chrome-extension#511] opened 2016-09-10 23:37 UTC
after update on extention i haven't recive any tests....can any one help me?
i did everiting and i'm ready for work hole day...
i even reinstal extention but stil same... not even one single test...

**Comment by GB-M** [comment] 2016-09-10 23:48
I have had this problem as well. The extension does nothing when I click on it. Last night, after I updated it, it kept telling me that I was not logged in. Now, it does not do this, but it does indicate that I have clicked on it with a "ripple" sort of animation. The icon has NEVER turned green, as other people have mentioned. It has been completely grey since the update, and no text has been visible.

I have not been given any new tasks since the update.

**Comment by blagoslav** [comment] 2016-09-11 00:09
after hole day no tasks, i got now two test in row...

**Comment by noel4657** [comment] 2016-09-11 02:14
Got the same issue with @GB-M. No hits done for me since the update. Sent complaints to RF support but no one is responding.

**Comment by shosti** [comment] 2016-09-11 16:58
If it tells you that you're not signed in, you have to sign in at your portal profile page (that should log in the extension as well). Once you've logged in, clicking it again should turn it green.

If you follow these instructions and it still doesn't work, let me know your contributor ID and I'll look into it.

**Comment by gusttest** [comment] 2016-09-11 18:17
@shosti Then followed all the steps you wrote, I removed the extension, logged out and I logged back, reinstalled the extension, clicked on the popup asking to enter the account, clicked on the extension icon, and still the same.
Contributor ID: 36031711
Thank you.

**Comment by martinmay1985** [comment] 2016-09-11 18:49
I have the same problem as gusttest
Contributor ID: 18744137

**Comment by noel4657** [comment] 2016-09-11 21:52
Hi, @shosti mine still doesn't work until now.  Please help, here's my worker ID 34223271.  Thank you so much.

**Comment by CarlosBoggiano** [comment] 2016-09-12 02:34
Hello.... Don´t work today, my id contributor ID is 36887378, please fix this.  Thanks for all...!!!!

**Comment by JPierreS** [comment] 2016-09-12 03:21
Your extension only checks for work when it is green and not in work state.

If you see the not logged in and you are logged in, log out of your portal, log back in, then refresh the logged in page and click on profile.  For some reason the extension thinks you are not logged in even though you are - logging out, logging back in and refreshing the profile page after logged in often helps.

Also keep in mind there are less jobs on the weekend.

**Comment by MarinaCec** [comment] 2016-09-12 03:24
The message failed to fetch is coming when we are inactive??? I don't understand it yet

**Comment by MarinaCec** [comment] 2016-09-12 03:36
I rarely getting work, I don't know if the problem is the new extension, but I think q started a little earlier.
When rarely comes a job the message is written already "failed to fetch" and even refreshing the message does not come out and comes not work. Sometimes the message changes to "Another worker accepted the job before you!" but the message "Failed to fetch" come back, making it impossible to work.

**Comment by ponpit31** [comment] 2016-09-12 03:58
its the same cases.., since yesterday never get one job

**Comment by vidyutron** [comment] 2016-09-12 11:53
Since, the notification has been updated to v2.0, work notification has been very patchy. I am following the #508(disabling and enabling chrome extension manually) . But Even if I get one, unable to perform any work becoz of consistent "NO Virtual machine available" followed by "Too many requests" error, after which its almost impossible to get the task back. facing this issue before the notification update.

**Comment by MarinaCec** [comment] 2016-09-12 12:21
not work yet...

**Comment by shosti** [comment] 2016-09-12 17:31
@vidyutron We've been having some VM issues unrelated to the plugin. They should be sorted out now.

**Comment by shosti** [comment] 2016-09-12 17:42
@martinmay1985 you've been blocked which is why you can't log in.

@gusttest @noel4657 @CarlosBoggiano I looked through our logs and it looks like you all logged in successfully. If you're still having issues where the icon not turning green, it would be helpful if you could do the following:

1. Go to chrome://extensions/
2. Enable "Developer mode"
3. Click "Inspect view: index_prod.html" for the plugin (or something similar)
4. Look in the console for error messages and post them here if you see any

**Comment by Yhenko** [comment] 2016-09-12 17:59
@shosti Hi, same problem, 5 mins ago i finally a hit, but the extension not turn green ._.

Worker ID: 37750987 (My account is Active)

**Comment by shosti** [comment] 2016-09-12 18:02
@Yhenko again, please check for error messages using the above instructions.

**Comment by Yhenko** [comment] 2016-09-12 18:03
@shosti "index.js:12 Uncaught Error: only one instance of babel-polyfill is allowed"

**Comment by shosti** [comment] 2016-09-12 18:07
@Yhenko can you try refreshing (with Ctrl-R) in the console? Do you still get the error?

**Comment by Yhenko** [comment] 2016-09-12 18:08
@shosti Done, Ctrl+R works, no more error! =D, thx!!! (=

**Comment by gusttest** [comment] 2016-09-12 18:19
@shosti This error appear when open the console:
![image](https://cloud.githubusercontent.com/assets/22075052/18447238/20787986-78fc-11e6-9782-53c7151da8e4.png)

**Comment by shosti** [comment] 2016-09-12 18:33
@gusttest that's very odd. Can you:

1. click the "Network" tab
2. click that request if you see it (it should be highlighted in red; if not try Ctrl-R)
3. click the "Response" tab and screenshot

**Comment by gusttest** [comment] 2016-09-12 18:41
Well, I Ctrl-R, I clicked on the icon turns green for about 3-5 seconds and it makes turn green again.
With the extension 1.2, was the work normally, but since I updated to the latest version could not do any more work.
![image](https://cloud.githubusercontent.com/assets/22075052/18447847/bf3f92be-78fe-11e6-960d-58dfafe2c928.png)

**Comment by JrRandy** [comment] 2016-09-12 19:01
Not sure if related, but I have 2 computers (No, I dont use both at the same time).  1 computer works as expected.  Push the button, it goes green, wait, work comes.  
The 2nd PC however, acts a little different.  When I clicked the button, it did not turn green.  I found that odd, so went into my network console, and sure enough it was polling away under a grey icon.  A couple mins later, a job window popped, and the icon added the "work" banner all while the button is still grey.

PC1:  Win7, Chrome 52.0.2743.116 m (32 bit)
PC2:  Win10, Chrome 52.0.2743.116 m (64 bit)

Could it be the OS version causing the issues?  Or 32 vs 64 bit?  Not sure what other info I can provide to help guide us down the right path @shosti

**Comment by martinmay1985** [comment] 2016-09-12 20:10
@shosti 
blocked in the profile appears to me since last year
but until Friday could do work (if you check my profile you will see that history has no new entries since 2014)
I payment messages of rainforest to prove that is wrong with my Profile

**Comment by gusttest** [comment] 2016-09-12 23:38
@shosti When I clicked in the extension icon,and open the console I see the following message
**https://bouncer.rainforestqa.com/1/testers/67f3bf48-a2bc-4431-8f11-1d07c60b7bc7/work_available?info={%22email%22:%22%22,%22id%22:%22%22} Failed to load resource: the server responded with a status of 403 ()**
I use it in 2 PCs:
-Google Chrome v52.0.2743.116 m Windows10 64 bit
-Comodo Dragon v50.14.22.465 Windows7 32 bit
Both with the same error.

**Comment by shosti** [comment] 2016-09-12 23:49
There's a forthcoming fix that should fix this--I think it's the same problem as #526. Closing as a dup for now.

**Closed by shosti** 2016-09-12 23:49 UTC
