### ISSUE TITLE
Tabs opened by extension do not always result in work

### ISSUE THREAD

**Issue by helloworld111gh** [rainforestapp/tester-chrome-extension#8] opened 2015-11-10 00:07 UTC
Work from the extension often does not actually result in work, and gives a "opps, no more work!" error. This may be because the extension does not actually reserve a HIT when it gets a link.
Possible Solutions:
- Try to reserve a HIT via whatever API that uses using the link, and ensures it reserves one before opening a tab
- Tie HIT's to links

**Comment by ukd1** [comment] 2015-11-10 22:39
@helloworld111gh correct, it doesn't reserve a hit, it checks if there is one available, and opens a new window to reserve it. If in this time someone else gets it, you may end up with an "ooops".

Part of the reason is the speed which some people are hammering the API; I've implemented rate limiting, which should help, but some people are still pushing hard.

Anyway, later today we'll be turning off all access to hits which don't come direct from the provider (mturk or CrowdFlower)... OR via the plugin; so the shared links won't work as well for testers more. We want everyone to use the plugin :+1:

**Comment by ukd1** [comment] 2015-11-10 22:40
@helloworld111gh regarding should it reserve a hit, it's totally possible to do - but I'm waiting before implementing to see how much this happens AFTER we stop the old-hacky-methods of getting work.

**Comment by helloworld111gh** [comment] 2015-11-10 22:56
Unclear about the change you say will occur, clarify? (Ex. Shared links,
turning off hits)

**Comment by pscohn** [comment] 2016-01-29 17:43
Closing as duplicate of https://github.com/rainforestapp/tester-chrome-extension/issues/22

**Closed by pscohn** 2016-01-29 17:43 UTC
Labels: enhancement
