### ISSUE TITLE
less jobs since last extension update

### ISSUE THREAD

**Issue by MarinaCec** [rainforestapp/tester-chrome-extension#580] opened 2016-09-19 11:58 UTC
since the extension update my jobs have reduced... it's only me or you too??

-------

it all started when released new testers, this is the truth

each update in rainforest it gets worse... in the first 5 months of this year rainforest was excellent. after that updated several times it only gets worse.

**Comment by CassianoTerzi** [comment] 2016-09-19 12:05
Here too, since the last update I'm getting few jobs.

**Comment by MarinaCec** [comment] 2016-09-19 12:08
My reduced 50% =(

**Comment by nikica13** [comment] 2016-09-19 12:19
It would be good if it only reduced mine by 50%, now I spend more on electricity waiting for jobs then earning. The worst is you need to be active all the time, there's only so many things I can do in the browser before I feel I'm wasting my time.

**Comment by hunt40** [comment] 2016-09-19 12:28
yeah its really bad nothing but another worker and rest is other errors,its hardly catch any hit,and not even worth it.they have a lot of testers but looks like they don't have enough hits to provide.

**Comment by MarinaCec** [comment] 2016-09-19 12:52
whenever I think the rainforest will stabilize they invent to update something and ends up getting worse

**Comment by uqbiii** [comment] 2016-09-19 13:35
If somehow you get a HIT, HIT contains maximum 4 steps and mostly have to report at 1st step. 👊

**Comment by MarinaCec** [comment] 2016-09-19 13:44
@uqbiii same here, or the VM is blank

**Comment by safae19** [comment] 2016-09-19 13:45
Same here, no job at all.

**Comment by Zubwins** [comment] 2016-09-19 13:48
Zero hits since the extension update!!   Is there any way to downgrade the extension?

**Comment by teteucalifornia2** [comment] 2016-09-19 13:52
Here the same thing happens . Reaches 50 % less work and only 10% without errors. This update really was not good for us testers, unfortunately

**Comment by Zamoraks** [comment] 2016-09-19 14:43
here almost never comes , and when it comes , another worker takes work ...

**Comment by gusttest** [comment] 2016-09-19 14:49
Here since I updated the extension stopped working, and I have to manually search for jobs.

**Comment by uqbiii** [comment] 2016-09-19 14:51
`Zero hits since the extension update!! Is there any way to downgrade the extension?`
Not sure, but i think you cannot do this, because i tried😄 and failed, i had their .zip file downloaded from Code page but it didn't work.
I think there should be an official statement on their portal about all the situation we and they are going through.

**Comment by Zamoraks** [comment] 2016-09-19 14:51
how do you look for jobs manually?

**Comment by MarinaCec** [comment] 2016-09-19 14:53
@gusttest how do you look for jobs manually?

**Comment by tulko** [comment] 2016-09-19 14:53
this is happening to us all

**Comment by gusttest** [comment] 2016-09-19 15:10
@Zamoraks @MarinaCec I leave this tab open, and I'm updating until a job (as this extension stopped to open the work automatically).
![image](https://cloud.githubusercontent.com/assets/22075052/18637077/9d1aa76a-7e61-11e6-8b97-c85aab5a3a4d.png)

**Comment by MarinaCec** [comment] 2016-09-19 15:47
@gusttest I don't understand, can you be more specific or paste this link here (wihout your worker id of course)

**Comment by uqbiii** [comment] 2016-09-19 15:59
@sweeneyapps Please take a moment to answer this situation, this happened to me about 20 times in last 2 days and its solution is re-installation of the extension. currently there are 23 showing and i have to re-install it again. I bookmarked the chrome web store link to this extension to install it easily. If you need the latest one, let me know i will upload it.
![](http://image.prntscr.com/image/3d426745016e488aa13008bcf40ac3ec.png)
@MarinaCec you can get this link from extension's background by selecting Network tab and clicking the page page by double clicking any link which starts from work_available.
![](http://image.prntscr.com/image/fbb115963961456b809d59741e73d363.png)

**Comment by sweeneyapps** [comment] 2016-09-19 16:33
@uqbiii in console, u can track XMLHttpRequests by right click "Log XMLHttpRequests" on console screen.  Also u can click on each errors for more information, such like Status Code in the Headers tab, and what's inside the Preview, Response.. .etc.

**Comment by uqbiii** [comment] 2016-09-19 16:40
Currently there are no errors showing because i installed it 15 minutes ago, as soon as they appear, i will create a bunch of photos for you, but to be honest, 0 Expectations.

**Comment by sweeneyapps** [comment] 2016-09-19 16:51
yeah I understand..   hopefully they switch over to websocket next month.

**Comment by Genesis2015** [comment] 2016-09-19 16:55
@sweeneyapps "...hopefully they switch over to websocket next month." what does this mean? Can you explain with few words, plesae? ;)

**Comment by bradpittvn01** [comment] 2016-09-19 17:02
My normal number of Hits per day before new extension was around 30 (sometimes 50). After new extension, in changing time, it was around 22 to 24 only. And today I got only ....3 Hits although today is Monday. Unbelievable!

**Comment by sweeneyapps** [comment] 2016-09-19 17:02
WebSockets is an advanced technology that makes it possible to open an interactive communication session between the user's browser and a server. With this API, you can send messages to a server and receive event-driven responses without having to poll the server for a reply.

More details: 
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API
https://www.websocket.org/aboutwebsocket.html
http://blog.teamtreehouse.com/an-introduction-to-websockets

**Comment by Genesis2015** [comment] 2016-09-19 17:13
@sweeneyapps I did not understand almost nothing of what you said, but anyway. :D Is this good for us? Are there any positive or negative aspects for us?

**Comment by sweeneyapps** [comment] 2016-09-19 17:18
Right now, we are asking the server for work every 30 seconds.  There's always no work.  That is waste of time for the server to listen to your computer.    With websocket technology, the server is always connected with your computer and it knows who you are.   It can send you job directly without your computer asking for job over and over again.  I hope you understand clearly.

**Comment by uqbiii** [comment] 2016-09-19 17:25
But with this, "Another worker and No VM" increases too.

**Comment by xakep99** [comment] 2016-09-19 17:37
Have you tried extension in real-life environment before releasing it?

**Comment by sweeneyapps** [comment] 2016-09-19 18:07
@uqbiii it's probably because old extension doesn't work correctly.  The old extension did miss some job and didn't polling correctly w/ the server.  So more people have the chance to grab job.   Right now, new extension is polling correctly and doesn't miss any job.    So we are competing w/ about 1,500 testers at the same time.   Old extension: some testers miss the job so then you might be competing w/ 2/3 of 1,500 testers.  More chances.   That's why I'm hoping for websocket because it's real-time connection.   Also RF can manage jobs assignment directly too.   It's up to them on how they design their websocket server.

The main problem with RF is...    We have like 5,599 testers logged on the system in a day average.   Mostly there's 1,500 testers on the system doing the TEST.    That's why Rainforest stopped New Testers program to reduce this problem..   The work demand is lower than number of Testers waiting for work.    That's why we are getting too many Another Worker got your job!   Also with No VM problem:  it is something that RF need to address.

**Comment by sweeneyapps** [comment] 2016-09-19 18:11
It's something Super Testers should discuss with Rainforest about websocket technology and how will Rainforest use it?   That is a discussion for another time.     Websocket can work like this,  you get a ticket number and wait for your number for the next available job.   Do u think that's fair?  There are many ideas on how to manage job assignment to Testers.   Websocket allows Rainforest more control on assigning jobs than old system.

**Comment by xakep99** [comment] 2016-09-19 18:18
@sweeneyapps Have anyone from Rainforest tried this new extension in real-life working environment?

**Comment by uqbiii** [comment] 2016-09-19 18:31
@sweeneyapps Thanks for the detailed answer.

**Comment by sweeneyapps** [comment] 2016-09-19 18:33
@xakep99  Yes and No.  They have 3 environments to test the extension in and they are (Development, Staging, Production).  We are on production environment right now.   The development is local computer where programmer test their extension on local computer with local server.   I don't know what they use for staging environment but they have a system where they test their programming before they release it to the public (Production).   Anything can happen in production environment because a lot of testers are on different kind of OS version, even on windows XP (old).   Maybe a super tester can answer those question because they re in close touch w/ rainforest than I do.

**Comment by qpPykT** [comment] 2016-09-19 18:51
1800 hungry testers still waiting the tasks :) A little mess from Rf side.

**Comment by xakep99** [comment] 2016-09-19 18:51
They should do it and see for themselves that this is the worst piece of software ever made. This error/success ratio is incredible - 100's to 1. It's in conflict with itself, application, server...

All those involved in implementing this extension (and not even tried it for a minute) should be ashamed of what they did. Realize your mistake and roll back to old version, sooner the better.

**Comment by qpPykT** [comment] 2016-09-19 18:56
@xakep99 
I think it will not happen. (old ver.) This ver will be improve.
Ps: забудь про старую версию она не вернётся уже.

**Comment by MarcHe1022** [comment] 2016-09-19 18:57
I dont understand why do they want to change everything at everytime. Everything were working ok, altough they had been making everything to not. Then suddenly they change for extensions which has never worked well and then they change the extension again which is working worse than ever. 
In a team which is winning  there is no need to make changes

**Comment by xakep99** [comment] 2016-09-19 19:01
@qpPykT First of all, this shouldn't have been released in this state. Second, something this wrong just can't be improved. Let me remind you that two versions were released in three days. That's not how things should be done.

**Comment by xakep99** [comment] 2016-09-19 19:04
"Did anyone test it? Yes and No."

This is everything there is to know.

**Comment by MarcHe1022** [comment] 2016-09-19 19:08
If the problem was just the few works it would still be ok. 
80% of works there is any problem like Failed to fetch, For instance,  I have wasted around 5 minutes  just to submit a Tic-Tac-Toe- job because its always happening any problem in the last part.

**Comment by sweeneyapps** [comment] 2016-09-19 19:33
let think about it.  The extension's only job is to just ask RF server if there is a job.  
1. Extension ask server 
2. Server response back w/ Yes or No.
3. If Server say Yes.. The server will give Job link to the Extension
4. Extension only open new tab with job link.

That is simple step to understand.   If the extension found job and open tab for you.  Then your extension is WORKING GREAT!   Nothing wrong with the extension.   It did improve over the time to make sure Tab is opening correctly.

Now, all the problem is ONLY THE SERVER PROBLEM!   Not the extension!   

Server Problem can be:

1. Too many testers log on.
2. Not enough VM to provide for all TEST
3. Too many Request (testers refreshing manually)
4. Bad Thing Happened (That's SERVER problem)
5. Fail to Fetch (That's between Computer and Server problem)
6. Alot of reason could happen.....   I can go on list on more reason! 

Now you see the bigger picture,  NOTHING wrong with the extension.   This extension is MUCH better than the older one.  I have seen the programming and it's AWESOME!

**Comment by begsoon** [comment] 2016-09-19 19:35
@sweeneyapps Nicely explained.

**Comment by hunt40** [comment] 2016-09-19 20:12
they have bigger problems then extension their infrastructure is mess,you cant do a single test without it giving you a any kind of error.QA company with very bad infrastructure system its not a i want to heard from QA company if i am customer.

**Comment by JPierreS** [comment] 2016-09-19 20:18
@sweeneyapps  Yes this is something we definitely should discuss - Hopefully this will be brought up in a future ST meeting.  It is unclear how exactly the WS will attribute work, but could be something along the line of giving work in priority to good workers first; ability to assign special jobs to specific workers, and many other possibilities.  As far as the getting a number and waiting in line for your turn, that in theory might be fair, however this will mean complete dilution of work, which means far less jobs for each individual workers, with some days/weeks nothing, if it really works based on the "wait in line" rule.  I honestly do not think it will come to that.  Whoever is online to accept a job might get it, if available, as it is currently, only with some changes, as in you either get a job or get nothing (no another worker - providing work gets assigned first then passed to you).  I guess we will all know when it happens !

In an ideal world, the GOOD workers, honest workers, those who follow rules and report what needs to be reported, should get the jobs first and get more jobs.  I think people have to EARN their trust and prove their work.  this would provide less incentive to cheaters and bad workers I believe and also be fair and rewarding to those who invested a lot of time in this task and do a good job!

**Comment by xakep99** [comment] 2016-09-19 20:18
People tend to believe their own eyes.

Extension may be perfect but it is in conflict with server. 

That's little picture, big picture, every picture and, most likely, no picture at all.

**Comment by JrRandy** [comment] 2016-09-19 20:36
Every week someone is posting on here about not enough jobs.  This is not new with this extention, it will not be new with the next version of the extension.  The fair statement would be "The previous extension worked better for ME" and to be honest, what works for you might not be best for the team as a whole.  I see about 15-20 people that are consistently complaining about them not getting jobs, extention not working properly, or whatever the case is.  And based on current stats, there were 5,604 testers logged in over the last 24 hours.  Lets go worst case scenario, and say 50 people are complaining.  That is still less than 1% of all testers.  I am still getting roughly the same number of jobs as I was getting before, somewhere between 20 and 40 during weekdays, and lucky to get 10 on weekends.  There has been no change for ME on the distribution of jobs.  What I have noticed, is alot more short tests (3-5 steps) which in turn made it appear that I was doing less work, when in fact it was roughly the same it was just worth a lot less than when I was averaging 15 steps a job.

I also noticed that someone above was complaining about 22-24 jobs in day.  To me, that is normal.  Perhaps the work is just being more evenly distributed now, and you are no longer getting a larger piece of the pie than the average worker?

**Comment by mojenLXXXIII** [comment] 2016-09-19 20:51
@sweeneyapps i don't know if i am the only one who noticed this but jobs like naturebox ,RF apps, avent has suddenly disappeared , i wonder is Rainforest start automation testing ?

**Comment by sweeneyapps** [comment] 2016-09-19 21:15
@mojenLXXXIII you'll have to talk w/ @kristen-allie

**Comment by sweeneyapps** [comment] 2016-09-19 21:21
Let me tell you a story....

Mr. Extension got a brand new bus and he is your bus driver to your workplace.  Every morning, he picks you up to take you to work.  You noticed his brand new bus with all of cool features.  Wow, it got a brand new TV and stereo system!  Also it got WIFI!   It also runs on electric power.  What's more!?  It got more seats.   You remember the old bus, it got 10 seats but this new bus got 50 seats.    

Mr Extension always get you to work on-time every morning.   But something happened at work, and you got upset and put all your anger on Mr. Extension.   Mr. Extension always listen to you and try to make you feel better.   But still Mr. Extension always take you to work on-time and you always complain about all the problem from work on the bus.    

Moral of the story?  Never blame the bus driver for the problem at work you had.

**Comment by JPierreS** [comment] 2016-09-19 22:16
I do not think the new extension is to blame, might just be coincidence though some people made up their minds ;-)) Initially when new extension came out I had no issues getting the same amount of hits.  Now assuming the new extension is working correctly - should not affect your number of hits.  What I did observe however, is that for some reason there are times when the new extension remains green but is NOT polling for work - with such errors in console such as ERR_FILE_NOT_FOUND.  Usually these can be resolved by uninstalling and re-installing, logging out profile, logging back in and refreshing the page.  Other times it could be 403 errors (CloudFlare issues for some testers and may occur at specific times and resolve on their own) or other issues, otherwise as long as the extension is synced with your profile and polling for work, you are doing fine - the extension does not create jobs, it simply queries the work state by sending your credentials, if it receives a false it will continue polling after a set interval, otherwise if true, it will pass along the URL that it receives.

The less jobs can be due to many reasons - more workers are now getting jobs compared to before because of the extension, compared to the job assignments on CF, so the dilution effect is in play,  also some customers may have ended their runs temporarily or rewriting their tests.

Also with the sad state of CF with less quality tasks, it appears now the main focus is with Rainforest.

As far as the automation concern, no, they haven't fully replaced humans with automation.  Even with 80% automation, there is still work left for humans, and with more work added, that 20% represents the same or even more work.   The more new testers they add the more the dilution effect, which is why the decision to close registrations was a good one, although a bit late lol.   I also have concerns that the WebSockets method might create even more dilution as now.  So only TPTB knows the real answers.

Let's hope for the best.

**Comment by xakep99** [comment] 2016-09-19 22:22
@sweeneyapps 

Here's more appropriate story for this situation:

Mr. Extension makes a phone device. It looks great and can dial numbers, you can hear what person on the other side talks and, also, what you talk can be heard on the other side. Shortly, it fulfills the purpose. The only problem with this perfect device is that it dials wrong numbers most of the time. Although users can talk to people on the other side, they started to complain but they neglect the fact that it's not maker's fault. It happens because of dated switchboards, lazy operators, broken infrastructure and many other reasons including users themselves: Some of them want to choose whom they wanna call and wanted their old, faithful and working devices back. Instead of being grateful for such perfect invention they complained over and over. That Mr. Extension couldn't understand and started to feel like he threw pearls to swine.

**Comment by khristianjose** [comment] 2016-09-19 22:23
I think rainforest is having a hard time since a week ago, i can do just like 5 jobs per day if i get luck lol

**Comment by sweeneyapps** [comment] 2016-09-19 22:51
@xakep99 good one!

**Comment by xakep99** [comment] 2016-09-19 22:54
Thanks. Now let's get serious and roll back to old working extension instead of this piece of art which doesn't work.

**Comment by Electroglitch** [comment] 2016-09-19 23:14
Well,the fact is that i never had to reinstall the old extension,not once! 
That alone makes it superior.
New extension on the other hand...must keep my eye on it all the time to be sure it's polling. -_-
So i wouldn't call it AWESOME programming lol

**Comment by xakep99** [comment] 2016-09-19 23:43
But it has TV... wait... it gets you on the bus.... no.... Yes and No..... Oh YES, it's WORKING GREAT!

**Comment by MarinaCec** [comment] 2016-09-19 23:52
unfortunately today I couldn't do 10 jobs to earn 10%, this extension is horrible

**Comment by Electroglitch** [comment] 2016-09-20 00:40
After newest fix extension keeps on turning itself off suddenly and asking me to log in 
fun fact i'm logged and and even funier i was doing the TEST

And offtopic but i really have to, customer success team or whatever it's called is not doing good job explaining customers rules of testing ,using the quotes placehoder properly etc
just like half an hour ago i had TEST where test author doesn't seem familiar with placeholder _
"Showing 40 of (some number) results"
I'm really tired of writting and explaning how the step should be written properly
i should be testing sites  istead!
p.s. bug count didn't increase what a surprise...

**Comment by xakep99** [comment] 2016-09-20 00:56
This is getting worse by minutes.

**Comment by Taruga** [comment] 2016-09-20 01:09
The extension is turning off while I´m working on a job. Unbelievable !

**Comment by sweeneyapps** [comment] 2016-09-20 01:11
btw, I'm doing alot of job right now.   while there's only 1,000 testers online..     I believe that we do get server problem when it's 1,500 testers online.

**Comment by sweeneyapps** [comment] 2016-09-20 01:13
@Taruga  the extension just reset to download new update from RF server.  That's why.   You just click it on.  :)

**Comment by Cocapesi** [comment] 2016-09-20 01:16
LOL is working perfect now, all jobs without errors and a lot of jobs right now.

**Comment by sweeneyapps** [comment] 2016-09-20 01:21
yeah that's whole of my point..  nothing wrong w/ the extension..   it's all server problems.

**Comment by xakep99** [comment] 2016-09-20 01:24
Why are you doing a lot of job now on the thing that was already working good?

**Comment by sweeneyapps** [comment] 2016-09-20 01:30
gonna make some money before testers run over here.  :)

**Comment by Vittalev** [comment] 2016-09-20 01:40
Just complementing the bus story:
![bus story](https://cloud.githubusercontent.com/assets/22078781/18654762/0d08160e-7eba-11e6-8ce1-aaa0b2165c62.jpg)

**Comment by Electroglitch** [comment] 2016-09-20 01:46
@Vittalev tickets selected and purchased using Busbud? :bus:

**Comment by shosti** [comment] 2016-09-20 03:29
Lots going on here, so let me take a stab at answering a few questions :smile:.

- I'd highly recommend against trying to downgrade the extension; even if you can get it to work correctly now, it will almost certainly stop working in a few weeks or a month. 

- There shouldn't be a difference in job assignment between the new and old plugin, since they use almost exactly the same process for assigning jobs. However, there's always the possibility of bugs popping up. The `ERR_FILE_NOT_FOUND` error is kind of worrying (and unfortunately that type of error is hard to debug remotely); if someone could post a detailed screenshot of the request (under the "Network" tab of the chrome inspector) I'll try to look into it more.

- @sweeneyapps is 100% correct that most of the terminal issues you run into ("failed to fetch", "no VMs", "another worker...", and so on) are not directly related to the extension but are problems with our tester terminal/VM infrastructure. We're working on hard to make the VMs more reliable while keeping up with increased load/demand, but it's a gradual process.

- *However*, certain errors occur because multiple people ping the server and get "work available" at the same time (especially the "another worker..." message). These should hopefully go away once we roll out WebSocket-based work assignment (which should be over the next few weeks).

**Comment by MarcHe1022** [comment] 2016-09-20 03:48
Im pretty sure that at least 95% of people which has commented on this topic agree that there is happenning a great loss of jobs on the lasts days, which has started in the same time of that new extension were implemented.  And I dont know if "just" a growing of new testers (I dont know where and how did they come...) was enough to make us lost 60% of the ammount of jobs  which we were doing some days before this extensions.

We know better these chenges of RF, in every new chenge a new problem.  I think you could be humble and admit the error of this updating and get back to the old methods, like you admited when you had changed the layout of terminal for the first time, and nobody were achieving at least 1 job because hard problems and after 1 hour  you get back with the old layout for some days more.

**Comment by andrianr** [comment] 2016-09-20 09:20
4 hours and only 3 hits...  4-6 steps
Who has more?? ;))

**Comment by huynhxuanvinh** [comment] 2016-09-20 11:40
it's really strange that there is no test from the site rainforest as usually. This makes the number of test decreased clearly.

**Comment by hunt40** [comment] 2016-09-20 12:35
no virtual machine ,another worker,this both message i will see on my dreams as a nightmare for a long time thats for sure.cant wait when they switched sockets its make it or brake it for me.

**Comment by jackqc** [comment] 2016-09-20 13:16
Hmmm ... according to "Manage extensions" my extension is version 2.02 ... same as last week. Now while last week wasn't great, Istill could get some jobs. Today I only seem to pick up "no virtual machina available", I can usually reload like 6 times or so until I get "another worker" instead of "no virtual machine", I haven't managed to get a single live hit today yet.

**Comment by elpanatibu** [comment] 2016-09-20 14:01
this is total madness. so much so that I am about to stop doing RF. I did make about 30 hits per day to make maximum 4 per day or none now. I spend more than 20 hours glued to the computer to make 4 jobs? before the new extension, I earned like 50$ a week. now i make 6$. and sorry for my bad english.

**Comment by Zubwins** [comment] 2016-09-20 14:14
Today, I spend all day sitting in front of my laptop and got only 2 hits.

**Comment by irishclouds** [comment] 2016-09-20 15:35
But the number of hits may change if i change the PC? In my office 10 hits this morning, now at home no hits this afternoon...:(

**Comment by MarinaCec** [comment] 2016-09-20 16:23
it all started when released new testers, this is the truth

each update in rainforest it gets worse... in the first 5 months of the year was exellent, after that updated several times and it only gets worse.

**Comment by uqbiii** [comment] 2016-09-20 17:11
@MarinaCec I agree with you, because of **NEW TESTER** including me, you are facing billions of troubles but can you please tell me how much tasks are you getting in last few weeks? Around 20-30 in weekdays!!! Because i am getting the same or higher amount, and one thing more that most of the testers who registered new account are facing problems with their existing accounts, they know about rainforestqa already and that's why they demanded to open registration. I also want to request from RainforestQA to please tell us the exact numbers of new registration and also tell us the number of Inactive accounts so it will be clear that 500-600 new testers can't make your Perfect system buggy. 😃 😞. First task i completed in **2014-07-22 21:17:36 UTC** but because of some issues my title is changed to New Tester.

**Comment by MarinaCec** [comment] 2016-09-20 17:41
@uqbiii 15/20 jobs per day has been a lot in the last few weeks...

**Comment by uqbiii** [comment] 2016-09-20 17:56
Dear!!! Everyone is facing the same problem, everyone who have posted in this thread, facing the same problem, if all the 6000 testers are not posting, that doesn't mean they are not facing this problem. From 08:30AM PKT to now(10:54PM) i got 10 jobs, the highest was 36c and i am expecting around $0.18 bonus and there maybe some testers who are not expecting even this. Another thing, some regular jobs are not appearing, like NatureBox and Rainforestqa's own tests. So there is a possibility that we are facing this situation because Site Owners are not releasing enough tests for us to reach 20-30 HITs per day. 🙇

**Comment by MarinaCec** [comment] 2016-09-20 18:06
hahahaha man, you are not understanding what I mean, nevermind

**Comment by kristen-allie** [comment] 2016-09-20 19:23
Hmm, I'm going to talk to @shosti about what's going on. Thanks for your patience!

**Comment by MarcHe1022** [comment] 2016-09-20 19:43
3 hits in more than 4 hours.  
and more updating is coming, and more bugs and less jobs..
I think that RF is doing the maximum to avoid to pay the 10-jobs-per-day-bonus to workers

**Comment by Electroglitch** [comment] 2016-09-20 20:47
@MarcHe1022 C'mon man ,now you turned it into conspiracy lol :laughing:

**Comment by uangonline** [comment] 2016-09-20 22:42
@MarcHe1022 I think CIA told them to do so lol.:laughing:

**Comment by Quwerty** [comment] 2016-09-20 23:02
Not everything is so bad with these last few updates, at least I'm back to practicing guitar, and I found my playing is getting better with every another worker :)

Now seriously, to who ever is reading this from Rainforest team, we don't really need more than 30 - 40 tasks a day, but what we need is a task with 20+ steps. Micro tasking is ok, but his is nano tasking, and the way it goes it will turn in 2 step tasks (one of which is redirection step).

The way things are going right now, I honestly see more and more people looking for alternative and slowly leaving RF, so for the project's sake please listen to what testers have to say and fix these issues.

All the best!

**Comment by JrRandy** [comment] 2016-09-20 23:19
@Quwerty That is only a valid statement if A) They didn't already have more testers than they do work, and B) People who actually said they were quitting actually quit instead of just complaining about the lack of tasks.  And even if B did happen, there are people posting all the time asking when Rainforest would open up again for new testers.  

I understand the lack of work is annoying, but you also need to understand that online work is a supply and demand system.  Right now there is more workers than there is work and it has 0 to do with the extension.  I would recommend for those people "sitting at the computer all day not getting work" to find another alternative to supplement during the downtimes.  There are always lots of crowd flower tasks as long as you have the accuracy rating to get your badges, there are always tasks on mTurk, and there are a myriad of other places to make money online as well.  If anyone is hanging their hat on only rainforest, they are making a mistake.  No 1 task is going to be consistent enough for you to live off of.  You need to diversify so that you always have a steady stream of income.

**Comment by begsoon** [comment] 2016-09-20 23:19
The biggest problem is that skilled testers,who did more than 10 000 tests, will start looking for alternative.No one will work for 5$ in 8-10 hours..
I hope that these bad days of testing will be gone soon

**Comment by JrRandy** [comment] 2016-09-20 23:22
Number of tests means nothing.  You can do poorly for a long time, and still hit 10,000 tests.  I have seen lots of screenshots where people had 8 or more rejections in a single month, and 5000+ tests.  Others have only 1000 tests, and no rejections.  Which is the "skilled worker"?

**Comment by Electroglitch** [comment] 2016-09-20 23:54
Many of you are claiming to be "Old" testers but if you really are, you'll remember much much worse times than now  ,there were times i thought :"Rainforest is really done this time." Boy, was i wrong ... :wink:

**Comment by VeryDisappointedTester** [comment] 2016-09-21 00:43
Is it extension? Is it server? Is it gremlins? WHO CARES!!! I had 15-30$ every day (mon-fri) for 12+ hours active job requesting. Today i earned less than $5 for 12 hours of activity. This is 3rd week that this is happening. 

@JrRandy
"Find another alternative to supplement during the downtimes" 
If i find alternative I WILL NEVER COME BACK!!!! Quality of my work is good, i got invitation for exploratory testing. I didn't just clicked YES until i reached 9700 hits.

9700 hits for what??? I invested almost one year of my life in this. Every working day (mon-fri) spending 12-14 hours active. Staying awake until 4 AM because i live in Europe and in my daytime there are very few jobs.
My reward??? In the last 15 days i can't earn more than 5-7$ and worst of all thanks to extension (still no sound notification) i have to stare in the computer like an donkey all day and click the keyboard every 6 minutes because someone thought that this is a great idea.
Every single change has been a disaster. Lack of customers? Are you surprised?
Who would pay for feedback - In your instructions you said click on the LOG IN but on the site there is SIGN IN. You want to take money from people and to put them on training how to write instructions?
Writing instructions is your job YES YOUR!!! We are doing your job for nothing. Wait, not for nothing! In fact we are losing money because when we report instructions we get pay only for steps that are completed. Great update!!! We are testers. We are not lectors of English language.
Once i thought that this could be something that i could do for the next 5-10 years. Now you are just one big disappointment.

**Comment by Vittalev** [comment] 2016-09-21 02:25
Just because you haven't found something else to do rather than sitting in front of your computer waiting for the next test, it doesn't give you the right to unload your frustration on others. If you are not happy, please make a favor to yourselves and try to find a meaning to your lives instead of whining. You are the master from you lives, do whatever you want, if you are not happy it is your fault, you are free to make whatever pleases you (unless Rainforest keeps you on a basement tied on a chair).

Whining can solve our problems at the initial stage of our lives, other than that it just serves to bother everyone around.
Constructive criticism is a thing, but most here seems to be just unloading their frustration.

AND WITH THIS I JUST UNLOADED MY FRUSTRATION ABOUT YOUR FRUSTRATION !

![anger_management](https://cloud.githubusercontent.com/assets/22078781/18695583/2c5ae3ae-7f89-11e6-890b-1d489d4a76d5.jpg)

![scalated quicly](https://cloud.githubusercontent.com/assets/22078781/18695431/1add417c-7f88-11e6-8538-23b160eb6359.jpg)

**Comment by MarcHe1022** [comment] 2016-09-21 02:37
nice, now it came the people talking about frustation and memes. 
I see that there are people still happy in doing 5 jobs by day while did 20 in the same period before.

Surely they will be happy with new updates and jobs wich will be even less than nowadays

**Comment by Vittalev** [comment] 2016-09-21 02:41
Sure, I'm always heppy :) because my happiness is not bound to the amount of tests I receive.
If your happiness is bounded to that I'm sorry :/

**Comment by MarinaCec** [comment] 2016-09-21 02:43
there are much ass kissers who is afraid to expose opinion here and admit that the rain only got worse in the last 3 months

**Comment by MarcHe1022** [comment] 2016-09-21 02:43
We are talking about the few tests in RF and that each update is a new desaster to workers. 
IF you want to talk about happiness or sending memes, I think that here itsnt the right place

**Comment by MarinaCec** [comment] 2016-09-21 02:47
@Vittalev I'm unemployed and I need money to eat, pay bills and stay happy :)

**Comment by VeryDisappointedTester** [comment] 2016-09-21 02:57
@Vittalev 
This is not whining it is a fact!
I unload my frustration on who??? Rainforest? They deserved it. Anybody else?
You said yourself - because my happiness is not bound to the amount of tests I receive.
So you are doing this when you dont have anything better to do. Some of us are actually earning for a living. We are not some kids that want to pay WOW or something similar. I invested one year of my life in this.
Just look at first AMA and see what Russell Smith said. From stories about pre-assigned work we came to this.

**Comment by MarinaCec** [comment] 2016-09-21 03:04
@VeryDisappointedTester exactly what I think, some testers are teenagers who want some money only for games, something unnecessary, they don't see the side of those who are really needing money to live and pay bills

**Comment by helloworld111gh** [comment] 2016-09-21 03:19
@MarinaCec If there are testers who are under the age of 18 they are violating the Crowdflower TOS (you need tax info for MTurk, so that's a good barrier to <18): https://www.crowdflower.com/legal/
The are also violating PayPal TOS, and they may be blocked if they signed any NDA's are they are unenforceable to minors, meaning they could leak confidential information without legal trouble.
I'm pretty sure that there are very few minors doing CF/MTurk, and even less doing Rainforest.

Generally, really good jobs don't last forever. On another crowdsourcing site I am on, there was a simple question answering job that paid $2.50 per answer. However, the client for that job ended it, and now that site is pretty much dead.
You should always have multiple sources of income when freelancing.

**Comment by JrRandy** [comment] 2016-09-21 03:21
Its not ass kissers, and its not people who don't understand that you need to make a living.  If I was working rainforest to pay my bills, and that wasn't cutting it, I would find something else.  Its as simple as that.  Complaining about not having enough jobs is not going to make more jobs appear.  1 job comes in, it gets dispersed to 1500 workers, 1 gets it, 1499 don't.  I don't know what else to say.  I think we can all admit there is less work than there was a month ago.  Ok, point made, most will agree.  That is NOT because of the extension, that is simply a lack of work.  This is for reporting BUGS with the extension, not for reporting that you are not getting enough work.  If you have a valid bug, please post a thread.  Otherwise, continue doing the jobs (or don't) and hope the work picks up again at a later time.

**Comment by uangonline** [comment] 2016-09-21 03:48
@MarinaCec If someone doesn't agree with you, that doesn't mean that someone is an ass kisser. As for the lack of jobs for recent weeks, it's just because there is more supply (worker) than demand (Jobs available), and it's a very basic economic rule. So i think you should be more patient.

**Comment by qpPykT** [comment] 2016-09-21 05:34
**This is not a job** it's just a freelance project for you and you should understand this **very clearly**. For everyone it can end at any time - no matter what might happen.

**Comment by nerdatwork** [comment] 2016-09-21 06:48
> there are a lot of ass kissers who is afraid to expose opinion here and admit that the rainforest only got worse in the last 3 months

@MarinaCec I understand you are frustrated but like you everyone else has the right to voice their opinions. Categorizing their responses the way you did is not expected when everyone else is **civilized** in their replies.

**Comment by huynhxuanvinh** [comment] 2016-09-21 12:49
finally, it backs !!!
I have catched a hit testing Ranforest site. Miss it so much. I used to think never see it again. :dancers:

**Comment by kristen-allie** [comment] 2016-09-21 19:56
@aleksasf @MarinaCec @VeryDisappointedTester, we welcome your feedback and concerns, but please be respectful. We monitor these issues, and any rude commenters will be blocked from posting. That being said, I've shared your complaints with the team.

**Comment by edufgimenez** [comment] 2016-09-21 20:06
Waiting for a task... A wild tab appears in browser, OMG a task to earn money,Loading... Application Error ( The same error showed 4x more) . Ok let's wait again for another task...  A wild tab appears again :O, Loading... Another work appears, Something Bad happens appears, Any other error I never seen before appears, back for waiting for a task and see all this again :/. This resume my last days at Rainforest. Please guys fix this.

**Comment by aleksasf** [comment] 2016-09-21 20:50
2 requests every 75.0 seconds:)
Put it on 1 per 3min if its going to solve the problem and get over with it.
Or just invest.

**Comment by aleksasf** [comment] 2016-09-21 20:53
I am respectfull, is irony illegal or insulting?

**Comment by MarcHe1022** [comment] 2016-09-21 20:56
Why kristen just  ask to be respectfull to people which is talking about the RF problems, but not about that guy who told about frustrated people and sending memes in a serious topic and received a negative feedback from 8 users??

PS: 75 seconds????

**Comment by kristen-allie** [comment] 2016-09-21 21:06
Everyone needs to be respectful, including those posting memes. Let's not be ridiculous, everyone.

**Comment by aleksasf** [comment] 2016-09-21 21:17
We are not, ignoring some nonsense, there are some serious questions in coments that no one answers. 
I asked why did you released new features testing on live system instead do doing the same thing your customers do?
 No one is here for fun so leaving people without proper working enviroment and job is not ok.

**Closed** 2016-09-21 21:18 UTC
