### ISSUE TITLE
"Another Worker Accepted"-Getting this all the day

### ISSUE THREAD

**Issue by nagabhyru** [rainforestapp/tester-chrome-extension#317] opened 2016-07-13 16:37 UTC
Hi friends,
Did any of you getting this message "Another worker Accepted" message while getting tests. Today I got this message too often (Almost 90%). Some times the extension turns YES and simply turns NO with out opening any test. If open they are end with "Another worker". Is this due to new interface or due to less work.

**Comment by ilegalna** [comment] 2016-07-13 17:15
Same here, all day.

**Comment by Angelituss** [comment] 2016-07-13 19:30
The same here all day, from Argentina

**Comment by rafaelzerpa** [comment] 2016-07-13 21:46
hello friends could help create an account to do work like this?

**Comment by rafaelzerpa** [comment] 2016-07-13 21:47
as I can be on the team of testers

**Comment by JrRandy** [comment] 2016-07-14 00:50
Over the last 24 hours, they have had 6500+ testers working (1256 online right now).  Chances are, someone who has a refresh slightly ahead of you was able to steal the job.  This is normal.  Annoying, but normal.  Please close this thread as this is functioning as designed and not a bug.

**Closed** 2016-10-16 16:59 UTC
