### ISSUE TITLE
We're sorry, we've reached the maximum number of concurrent testers we can support. Please reload and try again.

### ISSUE THREAD

**Issue by rnfrst** [rainforestapp/tester-chrome-extension#32] opened 2015-12-18 16:34 UTC
When a HIT is opened, the message "We're sorry, we've reached the maximum number of concurrent testers we can support." appears. Refreshing the page doesn't help. And then after 4-5 refresh, the message "You've requested this job too often" shows up. Much worse is that we have to wait 10 minutes before we could get another hit... Can you increase the number of times allowed to refresh a HIT that is already opened? Or better yet, add additional terminals when a batch of hits are released? Thanks.

**Comment by teteuc2** [comment] 2015-12-19 03:22
The truth is that the terminal is no longer the same for some time now. I am also having this error several times, terminal shared with others, screeshot errors. It's very difficult work that way. They could arrange and make the terminal was exactly as it was before.

**Comment by Genesis2015** [comment] 2015-12-19 10:13
I agree with @teteuc2

**Comment by Ranky2211** [comment] 2015-12-19 11:44
I also noticed that the terminal is bigger in size from the previous one and due to which problem in loading terminal that give this message or something went wrong message and also some hit have comment box to comment but not able to write in the comment box terminal covered half of the comment box.

**Comment by teteuc2** [comment] 2015-12-21 10:21
Another day and even errors. No official response. Please undo the change you made in recent months, much has worsened the terminal and the lives of testers.

**Comment by Genesis2015** [comment] 2015-12-21 10:26
Same to me :(

**Comment by rnfrst** [comment] 2015-12-21 17:44
Again this error for every hit

**Comment by mueller2511** [comment] 2015-12-21 17:58
you are right @rnfrst all the hits are getting this message only. its very hard to get the hit directly and after multiple restarts the hit is lost.

**Comment by Ranky2211** [comment] 2015-12-21 18:18
It is very hard to work either app error or max message

**Comment by JPierreS** [comment] 2016-01-01 08:17
This error happens from time to time still but what's odd is that sometimes this happens when there are only 400-500 testers online at once, and other times everything is running smoothly on 1200+ testers online.  What is even more frustrating is that now with idle policy we have 10 minutes to refresh that concurrent error to recover our hit or we lose it.  AND we have only 4 refresh retries, before we get told "requested too often" and have to wait 15 minutes for next job.

The problem is because the HIT session OPENS first, then redirects us to the concurrent worker screen, should never have to do that, because our session remains floating and active even though we are not working on the HIT !

**Comment by pvenkat7** [comment] 2016-01-31 06:22
to avoid "too often message" you can use "browser back and forward buttons" instead of hard refresh. If back button not available (with new test link) just go to any other link and go back to your test link.

you can do this for until terminal works.

note: hits goes invalid after 15 minutes

**Comment by JPierreS** [comment] 2016-02-01 08:21
Looks like a nice trick but I would not chance it as the job could then get marked as "fraud".

I have had bad experiences doing this before - and I found out by accident, when I used the back button instead of REFRESH, completed the hit, it was received and everything but marked as INSTANT admin rejection.  When I investigated further I was told that the job was marked as "fraud", in other words it's as if I never opened the job but opened it.  Fortunately the admin rejection was removed, but I think it is not safe to use back/forward button in that regards.  If they only give us a limit on job refresh it is for a reason.  Bypassing this would only put account at risk, now that we do not have the turk dashboard and Rainforest has hid every stat from us (stats that we have every right as workers to see) stats that all other companies show and don't hide, then it is better to be safe......I rather lose a hit than lose my account.

Cheers

**Comment by MrSonNguyen** [comment] 2016-02-10 16:57
yes same erros here.

**Comment by BonesKnows** [comment] 2016-02-11 19:30
same here

**Comment by CliX-er** [comment] 2016-03-23 23:38
"We're sorry, we've reached the maximum number of concurrent testers we can support. Please reload and try again." which leads to "You have requested this job too often. Please return the work.".

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx7faa18-c973-4158-b18a-736bcf0bbfe1&browser=any&hitId=3981217&sig=9a943f903c69d54a98714da18ed0a2594cec4a3c22a6bdebc26efc83d9012e84&turkSubmitTo=%2Fthanks&workerId=31505928

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx7001dd-df51-421d-9cbf-6da900cffcb2&browser=any&hitId=4560667&sig=1779f881e792ccbeb46f7e2ca86f1e69597e540a5b591a1483fcc3ae1c8d2041&turkSubmitTo=%2Fthanks&workerId=31505928

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx3495c0-2ee2-441c-940c-81fb98f773d2&browser=any&hitId=4581844&sig=2e949a16e28b0f1addcf22b83c87348f46bc35f680755b6be05391bd83bf4188&turkSubmitTo=%2Fthanks&workerId=31505928

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx1dab22-e7e3-43d3-8d65-15b370e38d72&browser=any&hitId=4534956&sig=e3c5a09a04d4d5cef3c0ca0ca31af1ec77bbbde5602a7b9b44ca00f8cc879ba3&turkSubmitTo=%2Fthanks&workerId=31505928

**Comment by marius11** [comment] 2016-03-24 11:45
There are no errors. Those messages are normal when someone accepts a job before you, or when there are too many testers on the same hit. 

You can try to refresh those hits, but it is not certain that you'll receive a hit.

**Closed** 2016-04-07 13:52 UTC
