### ISSUE TITLE
Extension installed on 2 computers

### ISSUE THREAD

**Issue by alpar25** [rainforestapp/tester-chrome-extension#630] opened 2016-09-27 17:19 UTC
In my household we have 2 laptops. I have the extension on both of them. I take care of using just one laptop/extension at the same. This worked in the past several times, but today a strange thing happened. I got a message from the extension that I'm disconnected because the extension is used on another computer. But just one extension was active. I had both laptops on and with internet connection and the extension installed on the laptops, but active on just one laptop. For a few hours worked fine. Than I switched for the another laptop. After some time I started getting the error message on the two laptops.I uninstalled the extension at one laptop, and then I didn't got this error message. 

The rule changed or this is a bug?

**Comment by nerdatwork** [comment] 2016-09-27 17:39
You can use extension on any ONE computer at a time. The other computer's extension will turn OFF. This is NOT a bug.

**Comment by alpar25** [comment] 2016-09-27 17:45
I made in such way in the past. But today was different. I had just one extension active but my extension turned grey and I got a message from the extension that "extension is used on another computer" or something like that. This message appeared more times. I resolved it with uninstalling my extension on my other laptop. So this is why I am asking that I had a bug or a rule change happened?

**Comment by sweeneyapps** [comment] 2016-09-27 18:09
@alpar25 yes, extension's code and rules has changed.

**Comment by qpPykT** [comment] 2016-09-27 18:13
@alpar25 
Recently was new update it's not a bug it's just protection of tricky people. You can't use the extention at the same time on the two computers or browsers and ect.

**Comment by alpar25** [comment] 2016-09-27 18:19
But can I have it installed on the 2 laptops? Can I switch it anytime if the extension is off on the other laptop? Or if this not possible, can I uninstall the extension on one of my laptop and install it on the another? Now I can use just one laptop for rainforest, but I will go to university and I would need to switch from one laptop to another like on weekend when I will go home. Is it okay toswitch sometimes?

**Comment by qpPykT** [comment] 2016-09-27 18:33
@alpar25 
When you use an extension on one of the computers you should to uncheck checkbox on other computers like this.
![rf](https://cloud.githubusercontent.com/assets/4960092/18886757/f336ea20-84f9-11e6-99b3-21ae0991e0ad.jpg)

**Comment by alpar25** [comment] 2016-09-27 19:01
Thank you for clarifying this.

**Comment by sweeneyapps** [comment] 2016-09-27 19:08
@alpar25 you don't have to disable or uninstall the extension.  It's just simple.  Just make sure one of them are inactive (OFF).  You won't get in trouble for doing this.

**Comment by qpPykT** [comment] 2016-09-27 19:48
@sweeneyapps 
Yes, I was wrong. Now I tried to use an extension on the two browsers it's works on the one of them if the extension state is OFF on another.

**Comment by alpar25** [comment] 2016-09-27 19:59
So I expereinced a bug in my case, because one extension was on and the another one was off?

**Comment by sweeneyapps** [comment] 2016-09-27 20:03
no bug :)

**Comment by alpar25** [comment] 2016-09-27 20:06
But why I got the message from extension that I'm disconnected because the extension is used on another computer? I'm sure that just one of the extensions was active.

**Comment by qpPykT** [comment] 2016-09-27 20:07
It's a feature :)

**Comment by sweeneyapps** [comment] 2016-09-27 20:13
yes, it does happen because the extension is still in communication with Rainforest server when it's inactive.  It's just letting you know that it is connecting to another computer to keep communication channel open.

**Comment by alpar25** [comment] 2016-09-27 20:16
So if my extension deactivate and I got this message, I uncheck the box of the extension on the another computer and I continue my work on the computer. In that way I didn't broke any rule?

**Comment by sweeneyapps** [comment] 2016-09-27 20:19
there's no rules.  You did not get in any trouble if you get the notification.   So don't worry about it.  It's not a bug or any warning.  It's just letting you know that other computer is connected to the server.   The server doesn't want to get confused which computer you are using.   So it just connect to one computer a time.   Nothing to worry about.

**Comment by alpar25** [comment] 2016-09-27 20:21
Oke. I understand it now. Thank you for your time. Thank you for clarifying this.

**Comment by JrRandy** [comment] 2016-09-27 23:13
Wait until you get the message when both computers have the extension "off" and it still lets you know it has disconnected you :)

**Comment by nerdatwork** [comment] 2016-09-28 03:08
@alpar25 If you are satisfied with the responses you got so far, please close this thread.

**Closed** 2016-09-28 06:43 UTC
