### ISSUE TITLE
extension is having problems

### ISSUE THREAD

**Issue by vanessa180479** [rainforestapp/tester-chrome-extension#16] opened 2015-11-19 18:23 UTC
Good afternoon, the extension is having problems. Out that work is available (YES) but does not open the tab job. I hope your answer thank my ID: 33902955

**Comment by nerdatwork** [comment] 2015-11-19 18:54
They are working on it and the same issue that you are facing was reported by me in #14

**Comment by ukd1** [comment] 2015-11-25 00:58
@vanessa180479 closing as this is a dupe of #14

**Closed by ukd1** 2015-11-25 00:58 UTC
