### ISSUE TITLE
Help me, I'm not receiving payments!‏

### ISSUE THREAD

**Issue by danaidh** [rainforestapp/tester-chrome-extension#392] opened 2016-08-16 20:18 UTC
I haven't receive my payment, I've change my worker ID so it's no longer 37787035, i do not longer have that channel on crowdflower, I asked crowdflower about this and they said i have to talk to you guys, it's the 3rd time I send a ticket, please help me I'm working and not receiving any of the payments because of this, the new worker ID is 39094020. Please, help me!!

**Comment by uqbiii** [comment] 2016-08-17 04:02
Can I change my CrowdFlower ID used for payment?

> Notat this time, unless you already have more than one Rainforest profile. Each CrowdFlower account has a different Rainforest Portal account associated with it. If you have done tests and gotten paid using your new ID, you can use it by logging into its portal account and reinstalling the Chrome extension. Otherwise, it is currently impossible to create a new account through CrowdFlower since we aren't currently accepting new testers/new accounts.

Source: Wiki/Frequently Asked Questions

To receive payment into your new Contributor ID, you must have to complete a task from your preferred channel, which is not possible yet and you have to wait. 
How do I start testing for Rainforest?

> How do I start testing for Rainforest?

As of July 2016, we've stopped accepting new testers until the need comes up again in the future. We hope this will allow us to focus on providing better quality results to our customers, along with a better quality testing environment for all of you.

That being said, welcome to all the new testers that have joined us recently! We're excited to have you! Keep up the good work, everyone!
Source: Wiki/Frequently Asked Questions

**Comment by nerdatwork** [comment] 2016-08-18 08:45
@danaidh Have you done any job using **39094020** ? If yes have you claimed your profile ?

**Comment by danaidh** [comment] 2016-08-18 22:45
Yes I have. I've sent lots of support tickets, with no answer

**Comment by danaidh** [comment] 2016-08-18 22:59
@uqbiii not very helpful, but thanks

**Comment by nerdatwork** [comment] 2016-08-19 05:36
@danaidh Why cant you receive your payment on old id 37787035 ?

**Comment by HW71** [comment] 2016-08-20 14:26
Well, actually I have the same / similar problem:
I joined RF back in April 2014 through my N###x channel at CrowdFlower. For several different reasons I abandoned my N###x account some months ago and only work through C###e. Actually my N###x account has been deleted in the meanwhile.

Now the payments on RF are "pending" because my CrowdFlower Contributor ID for N###x is not valid any longer (of course).

I also did one of the "new" RF training jobs which showed-up some weeks ago, but even using this one I was always taken to my "old" RF account (maybe because of Cookies - no quite sure about that).

From my point of view this is a BIG design / architectural issue, because on RF side an account should be unique per mail address (or even per user name, because mail addresses could change, too) - but NOT per CrowdFlower contributor ID! I really don't get it why one would make his own system dependent on a third party?!

The best thing of course would be to offer CF-independent payment options (like Paypal) but I understand that this would be a major step. But the option to change Contributor ID should be available - especially since PTC accounts could be banned - or PTC sites could get out of business easily. What would RF do in such cases? 

I don't care about my 45+x bucks I already "earned" (but didn't get paid) - but I'm really disappointed in the way RF behaves here: no answer to any of my mails / "tickets" and obviously not willed to see the "big picture" (because this is definitely not some kind of "solitary case")! As long as they have such "strong" dependencies on CF they will get more and more problems as outlined by me or @danaidh . 

Really really sad...

**Comment by helloworld111gh** [comment] 2016-08-20 14:44
@HW71 Try changing the email on the Neobux RF account to a different one you control (if you use Gmail you don't need to make a new account, Google "Gmail alias"). Then login with whatever you made your CS account with.

If that does not work ask Crowd flower if your Neo ID bonuses can be moved to your CS id (do not reference Rainforest, just say bonuses)

Due to how Crowd flower works it is impossible to change contributor IDs without having that ID do a registeration job. This is as you cannot send bonuses to a ID if they do not do one of your jobs.

**Comment by HW71** [comment] 2016-08-20 16:01
Hi @helloworld111gh  

thanks for dropping in... Hopefully this could also help danaidh because I don't want to hijack his thread with my issue... :-( I just thought both problems might be related and I wanted to support him by showing that this "Contributor ID issue" might be more common than expected...

So just to make sure we have a common understanding - you ask me to do the following:

1. log-in to Rainforest Tester Portal "as usual"
2. go to "Edit Profile"
3. change mail address to a new one (I have two GMail accounts anyways, so I'd use my second one)
4. logout from RF tester portal

Now what do you mean with 

> "Login with whatever you made your CS account with"

Do you assume that I have a second RF account? Actually I'm not aware of that (but maybe I missed an important thing here ;-)  ) => As mentioned above I did a new CF job 919467 back in June 2016 from within C###e (so maybe at that point in time a new account has been created), but when I clicked the "Claim profile" link I saw a prefilled RF login form with my "usual" Rainforest credentials.

And assuming that I have such a second RF account (which I'm not quite sure about, but anyways): how would the pending bonuses get transferred to the "new" CS Rainforest account?

Sorry for asking, but I'd like to avoid messing things up even more... :-)

**Comment by helloworld111gh** [comment] 2016-08-20 16:07
Yeah, the steps are correct. You may need to confirm email before it will
save. Wipe your cookies though after you log out and before you try
claiming again.

You would have to send a ticket to Rainforest to get the money transferred.
Failing that, you could ask Crowd flower to link the two IDs together (do
not mention Rainforest if you do this, just mention bonuses)

**Comment by nerdatwork** [comment] 2016-08-20 16:17
@HW71 You didnt hijack this thread. The whole point is to have a single thread for same issue so rest assured you did the right thing. Have you sent a support ticket about this and if so could you tell me the date ?

**Comment by HW71** [comment] 2016-08-20 19:14
@helloworld111gh 
Thanks for the clarification and for taking care, Richard. 

Concerning this "transfer of money"-thingy I have severe concerns, because in other discussions and - if I recall correctly - also in one of the latest AMA sessions exactly this has been ruled out! There's no such thing like transferring money from one RF account to another. And that's exactly why I talked about a "design issue" earlier: I have a RF account with a unique user name. I even verified this account by phone recently, so RF "knows" who I am. Hence every 1-to-1 relationship to a third party entity like "CrowdFlower Contributor ID" will cause issues. Especially if such entities could become "invalid" because PTC sites shut-down their businesses or PTC accounts get suspended for whatever reasons.


@nerdatwork 
OK, thanks for taking care... Here's the history:

- **June, 25th:**
Sent a mail when I noticed that my pending payments didn't get transferred to CS. At this point in time I was not aware of multiple Contributor IDs.
Several weeks later (and with the help of some folks over there in the CS board) we figured out that my pending bonuses *might* be caused by the abandoned N###x CrowdFlower payment channel.

- **July, 18th:**
Opened support ticket 13856 with exactly this hint (probably wrong / old N###x Contributor ID used for payments).

- **August, 7th:**
Since I didn't get any reply to that I additionally wrote a mail to tester@rainforestqa.com.

- **August, 19th:**
After some further days without any feedback I decided to read the AMAs and wrote an additional mail to Kristen (though I'm not quite sure if the mail address I found was an official one which gets followed).

So shall I perform the steps as suggested by Richard above - or shall I wait if there are other options to sort this out?

**Closed** 2016-10-16 16:59 UTC
