### ISSUE TITLE
Not counted BUG

### ISSUE THREAD

**Issue by perat691** [rainforestapp/tester-chrome-extension#661] opened 2016-10-04 23:39 UTC
Some of the bugs i have found aren't counted in  the "TOTAL FOUND BUGS" statistic most probably because they weren't reported from the majority of testers.  The question is is it recommended to sent a ticket to the RF QA team.

**Comment by JPierreS** [comment] 2016-10-05 02:09
No.  Do not send support tickets about this. Support tickets should be about issues for which you do not have an answer for, ideally, account related issues.  They are backed up as it is, and there is nothing much they can do for you regarding this.

When the bug count does not go up it means majority of the testers in your group did not report it.

There are some valid reasons why this could happen (transient errors, etc.) and some less pleasant reasons such as yes workers, cheaters, etc (which seems to be the case most of the time) sadly nothing can be done about individual cases.

Hopefully Rainforest will accept help from trusted workers to check jobs and hand out rejections to those who cheat, as I think they have a serious problem with quality and yes I have been tracking things carefully now on my side, for obvious hard to miss stuff and rarely does my bug count go up as well.

People should try to not clutter support with questions or issues you can get an answer for most of the time on the forums or wiki, so that those who really need support can get helped in a reasonable amount of time.

**Comment by qpPykT** [comment] 2016-10-05 06:00
@JPierreS 

> Hopefully Rainforest will accept help from trusted workers to check jobs and hand out rejections to those who cheat, as I think they have a serious problem with quality and yes I have been tracking things carefully now on my side, for obvious hard to miss stuff and rarely does my bug count go up as well.

And why do you think that the trusted testers can help them in this. Rf run more than 100,000 tests per day and how many trusted testers they have 20 or 100? Trusted testers will not be able to review a huge amount of tests even if they spend all day on it.
Rf has nice tool for detecting yes workers and cheaters it's called "retrospective" but it's should be configured correctly for this kind of task. Then all workers will be able to report about yes workers or cheaters if they detect them and trusted workers or rf will be able to review these reports.

**Comment by JPierreS** [comment] 2016-10-05 15:07
Not enough with retrospective - obviously ALL jobs cannot be checked, but targeted ones, how ?  If for example you report a very obvious bug and your bug count does not go up ? This would be a good candidate and added to the jobs to be checked.  Currently retrospective only works if you click yes and majority workers click NO, not the same thing, this is used as a learning tool and has no impact on accounts.   Actually using crowd to check work would mean if you clicked NO and majority said YES, so this would also be used as a tool to catch cheaters more efficiently - of course one cannot check ALL jobs, good point, but they can tweak the process and catch more bad workers along the way.

**Comment by qpPykT** [comment] 2016-10-05 16:36
@JPierreS 
I know how retrospective works now. I'm NOT talking about No workers. You can see all of your tasks (except training hits) that you had done before if you know how to do it. Just now retrospective configurated on others failed job and yours passed job. If you can see all of yours previous tasks - you can detect bad workers and report about it. I often looking in my tasks after the retrospective had been added and I know how to respond the other pair on the same hits that I did and I seen some of the yes workers or bad workers.

**Comment by JPierreS** [comment] 2016-10-05 17:06
I know what you are referring to but I will not comment as this is not a feature that was officially implemented this way, and using it in such way might cause them to disable it.   Officially, this is a tool to contest job disagreement when you clicked YES and majority clicked NO.  It is NOT intended to being used to check all jobs or catch yes workers !  The retrospective is NOT a tool to catch bad workers, even if you think it is and making unofficial use, it is a learning tool - actual job checking and flagging bad workers, giving them rejections, is another thing - I speak for many of us long time skilled testers who are fed up to deal with the yes workers and bad workers all around, many have ruined CrowdFlower and the only remaining decent tasks, and many rely heavily on RF task and it's supplement income.

You can use the retrospective your own way, but I will use it the official way to report job disagreements when I click YES and others click NO, where screenshot proves I was right, that's it.  it is not meant to be "hacked" to be used the other way around, until RF officially announces it can.

**Comment by qpPykT** [comment] 2016-10-05 17:27
@JPierreS 
As you say it is a learning tool and I am learning through screenshots in my tasks not someone else's. For bad workers there are training tasks but many of them will be pass it succesfully. Retrospective tool have a big potential but it's not using.

**Comment by JPierreS** [comment] 2016-10-05 17:32
Well you are obviously one of the good workers wanting to learn, great ! and you obviously know how to use the tool to check any jobs, great too, ;-))) now, you might have noticed by now lots of jobs where people clicked YES but show no mouse interaction or the screenshot does not back up their YES or that they clicked YES to obvious quote mismatch and other flaws ? You might have noticed it right ?  now a trusted crowd could FLAG right away and either hand over a rejection or flag the account for an admin to review.  This is not the same as sending notes but this would instead go to official admins checking jobs and flag the job as priority to be checked.   This would be a separate function and nothing to do with retrospective, which is not used for that purpose.

**Comment by qpPykT** [comment] 2016-10-05 18:23
@JPierreS 
If they wanted they would have already given such access for "super testers".

**Comment by sweeneyapps** [comment] 2016-10-11 01:56
pretty much, it's not a bug.  Bug count increase only if the majority discovered the same bug.    let close this issue..   :)

**Closed** 2016-10-11 05:01 UTC
