### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by androwg** [rainforestapp/tester-chrome-extension#41] opened 2016-01-08 09:45 UTC
@pscohn rgnwldqa most of times gives "Application error an error occurred in the application and 
your page could not be seved, please try again in a few moments if you are the application owner check your logs for details"
should we report this or wait a while and keep refreshing until rgnwldqa site works ?
we need a clear response from you as we are suffering from this problem and we are in fear that if we report ,our work will be rejected,

**Comment by Genesis2015** [comment] 2016-01-08 10:36
Same here. An EXTREMLY annoying problem! I can't complete evean a single RF test w/o this kind of problems. It take more then half an hour to complete a test and if I have a luck and there are no more errors. :-1:

**Comment by macocha** [comment] 2016-01-08 11:45
Hey guys,
We've fixed the underlying issue, so this shouldn't be happening anymore.
Thanks for reporting this.

**Comment by Genesis2015** [comment] 2016-01-08 13:36
Thanks @macocha now everything works better... not perfect, but better then before. But as @androwg says: "should we report this or wait a while and keep refreshing until rgnwldqa site works ?
we need a clear response from you as we are suffering from this problem and we are in fear that if we report ,our work will be rejected?"

**Comment by JPierreS** [comment] 2016-01-15 04:09
@Genesis2015 I report this issue on a daily basis, several times, the problem is far from fixed.  it is intermittent.  It happens mostly with tests from rainforest (testing their own site / API)  I think the issue is with their host.  Sometimes I wait and refresh and it resolves, if it doesn't I report it.

If your screenshot clearly shows what you are reporting, and you report properly, then you should not worry.  Algorithm rejections are not against you, only hard rejections (admin verified ones, if you get too many of those in a 30 day period).  If you follow instructions (and yes RF knows how you interact with intermal and can reconstruct your session with the data they store), then you should be fine.  If you click yes when there is stuff to report, THEN you should fear those rejections because they will count against you, otherwise if you do your work properly, rejections won't count against you.

Trust me, I think nowadays I get mostly hits that require a report, I sometimes check with RF to make sure I'm ok, and so far it seems I'm not in any danger.   Most of the ones who get blocked are those who cheat intentionally or make too many mistakes / don't understand the task or follow instructions.

Cheers

**Comment by androwg** [comment] 2016-01-19 14:02
@macocha  problem reappears a lot nowadays

**Comment by macocha** [comment] 2016-01-19 14:49
@androwg thanks for alerting us. We are looking into the issue.

**Comment by Genesis2015** [comment] 2016-01-19 15:20
Same situation here :( I hope that you will solve the problem ASAP :+1:

**Comment by mukikuki** [comment] 2016-01-19 17:37
chrome extension opens test page whit application error  more than 20 pages now in last two hours

**Comment by JPierreS** [comment] 2016-01-22 21:56
I think the issue they are having is their hosting !  When they have volume of tests being run at once and testers, host is intermittently up/down (application error) and which in turn causes failed to take screenshot.  I think the main "issue" is infrastructure not able to handle the load.  The hits I get during my night name are lightning fast - fast terminals, fast everything, :D  the ones I get during the day some days is like being in a bloody nightmare, it's torture some days, so yeah it's obvious it's infrastructure related.

They simply have to add more Commodore 64's  :=)))

**Comment by pscohn** [comment] 2016-01-28 19:13
Closing, seemed to be an intermittent issue we had last week.

**Closed by pscohn** 2016-01-28 19:13 UTC
