### ISSUE TITLE
error VM and extension 

### ISSUE THREAD

**Issue by Elizabesita10** [rainforestapp/tester-chrome-extension#532] opened 2016-09-12 17:49 UTC
Hello very good morning I wanted to announce that I found some errors in both VM and extension.

VM errors
First error:
something is happening
second error:
An IO Error occured: ioError, Error # 2031
Other error:
A security Error ocurred (Error # 2048)
Please check you can connect to http .....

I got all these errors in a single work of 100 steps, which hampered me a lot to finish it.

I wanted to add something more, when I finish work and I click back to return to the browser, I can again perform the work again, although it is presented or completed, that did not happen before please verify that.

another error extension is:
although I have a job open, open another job at a time.
and other errors and my colleagues have mentioned, otherwise all good.

**Comment by shosti** [comment] 2016-09-12 18:31
This is a duplicate of several other issues. Closing.

**Closed by shosti** 2016-09-12 18:31 UTC
