### ISSUE TITLE
Interfacet Update and "You have..." message

### ISSUE THREAD

**Issue by MarinaCec** [rainforestapp/tester-chrome-extension#261] opened 2016-06-29 16:53 UTC
The new layout is very weak color, I can hardly see and is very annoying to have to zoom out to see the whole screen, many small letters... and I don't know, but after the update also have the message "You have Reached the maximum number of unsubmitted assignments. So we are fair to other workers, we stop you doing too much for us at once. you can complete the other assignment (s) and refresh this page, or simply return this hit. " over an hour... This is very annoying.

**Comment by zfonck123** [comment] 2016-06-29 16:55
i want back the old school. the new school is soo bad..

**Comment by GersonTavare** [comment] 2016-06-29 17:01
Yes, I don't like the new layout too, the terminal is extremely small. The less things on the screen,  better, so we can see a big and clean terminal. Btw, the most annoying thing on the day was the errors caused by layout change.

**Comment by priggy** [comment] 2016-06-29 17:02
I am getting the same error after i finished IOFFICE job... that job crashed everything.... counts as submitted, lasted for 0 seconds??? :O and ofc is now listed under rejected...

**Comment by CassianoTerzi** [comment] 2016-06-29 17:23
I think, instead of trying to fix all the errors why they prefer to change the interface ? The past 2 weeks the terminals have been very slow, with "falied to screenshots", Oftens with just one refresh page, with messages as "You have..." "We're sorry....", since the RainForestQA got back to CrowdFlower, We all have been harmed .

**Comment by MarinaCec** [comment] 2016-06-29 17:25
@CassianoTerzi I totally agree, since the RainForestQA got back to CrowdFlower, We all have been harmed .

**Comment by zfonck123** [comment] 2016-06-29 17:33
any update in you have reached ?

**Comment by MarinaCec** [comment] 2016-06-29 17:34
@zfonck123 nothing, still the same, 2 hours with that message "You have reached the maximum..."

**Comment by BonesKnows** [comment] 2016-06-29 18:17
i have the same problem with "You have reached the maximum..." message..

**Comment by st53stefanov** [comment] 2016-06-29 18:52
more than 2,5 hours...
You have reached the maximum number of unsubmitted assignments....

**Comment by samballode6** [comment] 2016-06-29 19:04
Same here.

**Comment by luisdanielvc** [comment] 2016-06-29 19:06
Same here

**Comment by AndyARB** [comment] 2016-06-29 19:13
Same here.

**Comment by GersonTavare** [comment] 2016-06-29 19:15
Day played in the trash. More than 3 hours on maximum error. Only because they want a worse interface, that will disturb because of small terminal size. Nice idea.

**Comment by marius11** [comment] 2016-06-29 19:20
@GersonTavare I haven't noticed any differences in the size of the terminal with the new interface.

**Comment by zfonck123** [comment] 2016-06-29 19:44
about 4 hours+

**Comment by samballode6** [comment] 2016-06-29 19:49
Is good now..

**Comment by MarinaCec** [comment] 2016-06-29 19:53
about 4 hours+

**Comment by zfonck123** [comment] 2016-06-29 19:55
:( me 5 hours  and nothing T____T

**Comment by GersonTavare** [comment] 2016-06-29 21:05
@marius11 I made only two hits with this new interface, but both had the sides cutted, very strange.
More than 5 hours and counting.

**Comment by nuevao** [comment] 2016-06-29 21:11
![captura](https://cloud.githubusercontent.com/assets/16979522/16468974/87ef4376-3e1c-11e6-8030-700debe11836.JPG) 

I hope it's a mistake, because otherwise it means they want to leave out those who took more time with them.

**Comment by ichithekiller** [comment] 2016-06-29 21:22
Just got one HIT after 5 hours of waiting and it's back with "You have reached" message.
Oh well, Skyrim time, then.

**Comment by MarinaCec** [comment] 2016-06-29 21:28
@nuevao @ichithekiller the message change to "another..." for a few minutes here, but then the "You have reached the maximum..." come back

**Comment by st53stefanov** [comment] 2016-06-29 21:38
@MarinaCec  same here.I think the old: (We're sorry, we've reached the maximum number of concurrent testers we can support. Please reload and try again.) is now replaced with "You have reached the maximum..." And this is definitely a bug.

**Comment by Electroglitch** [comment] 2016-06-29 21:38
Maybe i'm wrong but this looks to me like same situation as #17

**Comment by GersonTavare** [comment] 2016-06-29 21:40
@Electroglitch but since this time we just can use one account. I guess it's a problem generated by layout change, like the new rejection errors.

**Comment by nuevao** [comment] 2016-06-29 21:44
@Electroglitch # 17're right, I think it's the same problem, and according to comments RF was caused by some users were using multiple accounts to make the hit's

**Comment by uangonline** [comment] 2016-06-29 21:44
It seems the problem is for everyone. I also encaunter the maximum unsubmited, but not always though.

**Comment by nuevao** [comment] 2016-06-29 21:45
Clearly it is a mistake because in my case and I'm sure in yours not use multiple accounts.

**Comment by Electroglitch** [comment] 2016-06-29 21:46
@GersonTavare Yes you are right you can work only account but 
my point is if you ever had any other account no matter if you use it or not 
system will give you this message and you'll never get any test do 
so whatever was implemented and fixed in #17 looks like its broken with this update

**Comment by uangonline** [comment] 2016-06-29 21:47
@nuevao : I think it's a bug, not because someone using multiple accounts since it's start to happen today when they tried to use the new interface.

**Comment by uangonline** [comment] 2016-06-29 21:49
It's useless to make multiple accounts to find a hits, since it eill only give you an error.

**Comment by nuevao** [comment] 2016-06-29 21:52
guys read https://portal.rainforestqa.com/

**Comment by Electroglitch** [comment] 2016-06-29 21:57
That's not the point offcourse you can't do hits from more than one account 
ok Let's look it this way , let's say you had account on neobux once in past but in meantime switched to elite because of no fees etc...
and after you continued to work only on elte for months with no problems,
today, just as with that update in november ,
somehow system sees 2 accounts linked to 1 same place and somehow get's confused and result is you get nothing on any account
If there is no work ok message> Another worker....
 but if there is work message >You have reached the maximum..
I know i've experienced this for like more than 15 days back in november

**Comment by uangonline** [comment] 2016-06-29 22:00
@nuevao Tell you the truth that i prefer the old interface since it seem lighter than the new one. With animated interface it will make things heavier.

**Comment by rahayusri** [comment] 2016-06-29 22:02
@Electroglitch I only have 1 account but still get the same error messege.

**Comment by uangonline** [comment] 2016-06-29 22:12
@rahayusri Yap eventhough you have 10 account from different channel, you still can only use 1 at a time. So it's definitely a bug.

**Comment by tulko** [comment] 2016-06-30 00:25
40 tes per day to less than 10, great progress

**Comment by MarinaCec** [comment] 2016-06-30 02:39
@tulko same thing here, very disappointed

**Comment by Electroglitch** [comment] 2016-06-30 19:59
@MarinaCec Since everything seems to be back to normal you should close this

**Closed** 2016-06-30 21:04 UTC
