### ISSUE TITLE
Extension gave me two hits at once

### ISSUE THREAD

**Issue by helloworld111gh** [rainforestapp/tester-chrome-extension#746] opened 2016-10-29 07:17 UTC
For some reason the extension gave me two training HIT's at once. The second HIT closed the first HIT's tab, the extension did it's alert twice, and I had to drag out the first HIT from my history in order to turn off the "WIP".
I can send screenshots of console logs (which also have the URL's), just tell me where to send them.

**Comment by shosti** [comment] 2016-10-31 17:25
Please send logs (+ you contributor ID) to emanuel@rainforestapp.com

**Comment by shosti** [comment] 2016-11-01 01:26
Thanks for your help debugging the issue. Unfortunately, I haven't been able to reproduce the bug with the information I have available. We already have a bunch of code that tries to prevent this scenario, and it was probably an extremely specific sequence of events that caused the double-assignment. 

I'm going to close this issue for now; please reopen if it happens again.

**Comment by helloworld111gh** [comment] 2016-11-17 02:39
someone on the forum is reporting they experienced this: https://forum.rainforestqa.com/t/got-2-hits-at-the-same-time/3246/1

**Comment by HW71** [comment] 2016-11-18 21:39
Few hours ago I had the same issue: 
First tab opened with mavericks-safari9 VM and I started working on the Job by pasting the initial URL into the browser in the VM. This worked fine, but when I hit enter the browser didn't load the URL for whatever reason.

Soon after that a second Tab got opened with a training job and in the first tab I got "Invalid state"...

**Comment by shosti** [comment] 2016-11-21 16:45
(repost from forum)

OK I'm pretty sure I know what's going on. It's something like:

1. You get "pre-assigned" a job and a tab is opened
2. There's an error fetching the job, so you never get "actually" assigned
3. The terminal tells the plugin that there was an error, so the plugin turns off "WIP" mode
4. You get assigned a new job quickly so it looks like you got 2 hits at once

This is actually working as designed I think; it works that way so that tester terminal errors don't lead to long work delays. But I can see how it's confusing; what would a better way be? Should the old tab automatically close when there's an error?

**Comment by ukd1** [comment] 2017-02-18 01:09
@shosti can this be closed, or is this a thing?

**Comment by shosti** [comment] 2017-02-18 01:10
Let's close for now.

**Closed by shosti** 2017-02-18 01:10 UTC
