### ISSUE TITLE
More than 20 training jobs

### ISSUE THREAD

**Issue by vladfuller** [rainforestapp/tester-chrome-extension#411] opened 2016-08-23 18:47 UTC
Its normal to get more than 10 trainings hits?

Usually i get 10 or so and i ve received to my cf profile the msg sayng You passed a training lesson! Hi , Congratulations, you completed your last training lesson successfully! If your course is complete, you should get another email shortly.

twice...
I could be able to get the normal hits right now, but still getting training hits :X

**Comment by Ssamfisher** [comment] 2016-08-23 18:50
Same error, I'm getting a lot of training jobs

**Comment by vladfuller** [comment] 2016-08-23 18:50
I just took off my plugin... its really frustrating to get more and more jobs and im not getting paid =l

**Comment by Ssamfisher** [comment] 2016-08-23 18:51
I did more than 15 jobs. Reinstalled addon and continue th same

**Comment by madeuser** [comment] 2016-08-23 18:54
So... me and @ladystoneheart are not the only ones that got a lot of training jobs. I completed over 35 already. Is this a bug maybe?

**Comment by vladfuller** [comment] 2016-08-23 18:55
i think its a bug bro... u only need to complete 10 training jobs

**Comment by madeuser** [comment] 2016-08-23 18:57
@vladfuller glad to hear that! Thanks for the info! +1:

**Comment by madeuser** [comment] 2016-08-23 18:59
I can confirm that CF sent me 42 emails in which they tell me that I completed a training lesson. I'm so awesome! :))

**Comment by Ssamfisher** [comment] 2016-08-23 19:05
I'm going to turn off the addon, it don't stop

**Comment by ladystoneheart** [comment] 2016-08-23 19:10
Your training is complete! Hi ladystoneheart, Great news: your training is complete! You will now be able to do regular work for us! Happy testing! Rainforest QA Team p.s. view your profile here: https://portal.rainforestqa.com/..... Get our Chrome plugin here: https://chrome.google.com/webstore/detail/immdjpjbcikbffjifkbncgfbohbjicpo ref: 6793 




====>>> i still getting training jobs even i got many messages like this!

**Comment by Zamoraks** [comment] 2016-08-23 19:13
I am also facing the same problem.
it seems to me that the rainforest or decrease the amount of workers casting undue tests if remuneration to be blocked according to their mistakes.

**Comment by alncssk** [comment] 2016-08-23 19:13
I have the same messages, Lady stoneheart, what do we do?

**Comment by Ssamfisher** [comment] 2016-08-23 19:15
@Zamoraks but I only have 3 rejections

**Comment by ladystoneheart** [comment] 2016-08-23 19:15
@alncssk i really do not know. hehe

**Comment by josejecr97** [comment] 2016-08-23 19:16
i will turn it off ... is really unfair .

**Comment by Zamoraks** [comment] 2016-08-23 19:18
I hope to have my removed rejection , why is unfair , I already did the test .

**Comment by josejecr97** [comment] 2016-08-23 19:19
@Zamoraks  me too i got one and i did everything right !

**Comment by madeuser** [comment] 2016-08-23 19:37
I just received a normal job, it seems that the issues is fixed! Happy testing! :)

**Comment by Zamoraks** [comment] 2016-08-23 19:39
I still continue to receive , what did you do ?

**Comment by Ssamfisher** [comment] 2016-08-23 19:40
Same, I'm only getting training jobs

**Comment by madeuser** [comment] 2016-08-23 19:41
@Zamoraks @Ssamfisher nothing! I had my rainforest tester notifier plugin off for about 20 minutes.

**Comment by Zamoraks** [comment] 2016-08-23 19:43
I understand , I will do the same, may resolve .

**Comment by Ssamfisher** [comment] 2016-08-23 19:45
Same, comment here any new

**Comment by marius11** [comment] 2016-08-23 20:51
This is not unusual. I also received training hits when I already had completed 1,500 jobs.

**Comment by javicocuba** [comment] 2016-08-23 20:51
Same error, I'm getting a lot of training jobs, I took more than 20

**Comment by alncssk** [comment] 2016-08-23 21:07
ey marius11, and how you completed and I'm 53 jobs jobs training, and follow....

**Comment by josejecr97** [comment] 2016-08-23 21:50
still the same, i got 1 unfair rejection .. wtf is wrong ??????????????

**Comment by ando100** [comment] 2016-08-23 22:14
@josejecr97 mind your language please and check
https://github.com/rainforestapp/tester-chrome-extension/issues/410#issuecomment-241889115

**Comment by josejecr97** [comment] 2016-08-23 22:23
@ando100  my bad,  ok.

**Comment by Zamoraks** [comment] 2016-08-23 22:33
someone managed to solve this problem ?
 already I tried everything , not to come to training jobs ...

**Comment by slrojasc** [comment] 2016-08-24 00:46
I think it corrects itself ... either way, you should do the tasks correctly. I can and do normal jobs

**Comment by vladfuller** [comment] 2016-08-24 02:03
Well it was solved... i think it wasnt a bug, it just was a "Training Day"...

**Comment by slrojasc** [comment] 2016-08-24 02:45
"vladfuller": You may itself have been a "training day" but I know that two testers who did not have this "training"

**Comment by federicoall** [comment] 2016-08-24 03:55
same here for me and rejection.

**Comment by qpPykT** [comment] 2016-08-24 04:22
All testers receive training jobs when their work indicates they need to be retrained. Just go through that when it's needed.

**Comment by RezwanulHaque** [comment] 2016-08-24 04:38
Good to have training jobs, but I got 3 unfair rejection.

**Comment by qpPykT** [comment] 2016-08-24 04:50
@RezwanulHaque 
Are you sure that was unfair many testers don't see many things that they should see and know about it.

**Comment by RezwanulHaque** [comment] 2016-08-24 04:54
Well, that is my question also. I sent email to support to learn where was the problem.

**Comment by sweeneyapps** [comment] 2016-08-24 04:57
I am curious, whats the unfair rejections..  you got any example?

**Comment by nerdatwork** [comment] 2016-08-24 05:28
@vladfuller Can you show a screenshot of your RF profile ?

**Comment by Zamoraks** [comment] 2016-08-24 06:58
can not stand these jobs training , I made 43 and returned to normal, but this morning again returned to training works ...

**Comment by irishclouds** [comment] 2016-08-24 08:55
Same problems for me, only 2 rejection after 1 year yesterday night when i can't sleep for the earthquake in Italy, i have made some mistakes on the works, now only test job, also if RF notify me that i have passed and i can work on regular job. How i can solve this problem :(

**Comment by nerdatwork** [comment] 2016-08-24 13:14
Check this:[Why Training jobs ?](https://portal.rainforestqa.com/)

**Comment by madeuser** [comment] 2016-08-24 14:18
Thank you @nerdatwork. 
I have only one question: They said that a tester has poor performance... what does "poor performance" mean for rainforest if a tester has all of his tasks done correctly? I mean no rejections. I don't get it, you have poor performance and you receive rejections and you have good performance you don't get rejections. Plain and simple!

**Comment by qpPykT** [comment] 2016-08-24 14:48
Nice new improvement. Gold diggers and yes clickers will be happy.

**Comment by madeuser** [comment] 2016-08-24 15:00
@qpPykT I'm doing my best and nothing more, this is like saying believe and do not question. We are humans and it's normal to ask this kind of questions. I really appreciate the chance to work on this system, but rainforest could explain the way in which they categorizes poor performance testers and good performance testers if testers don't get rejections. In my opinion this could help testers to become more aware and be more focused on the work they are doing if they new for what to "look out" in a test in order to avoid a "poor performance" badge.

**Comment by xakep99** [comment] 2016-08-24 15:02
If people are not provided with proper explanation about what they did wrong, they won't be able to figure out how to improve their work. Without such explanation this is pointless.

**Comment by nerdatwork** [comment] 2016-08-24 15:05
I will update this thread with your concern @madeuser

**Comment by madeuser** [comment] 2016-08-24 15:12
@nerdatwork thank you!? Is this a good thing or a bad thing? :)

**Comment by rnfrst** [comment] 2016-08-24 15:20
@madeuser the reason behind this would only be between you and RF. No one could speculate here the reason why you and others are receiving training hits. Just keep in mind that having a rejection visible in your portal is not the only basis in testing your performance. If you are following the rules closely and reporting what needs to be reported, then there is nothing to worry about.

**Comment by madeuser** [comment] 2016-08-24 15:28
@rnfrst thank you for your answer. I'll try to get an answer from RF... 
Good day!

**Comment by maciejgryka** [comment] 2016-08-24 15:36
@madeuser I'm happy to look at your profile and confirm whether you were put in the "training sandbox" fairly, or not (please send a support ticket starting with `"This is madeuser"` if you want me to have a look).

However, at the end of the day "poor performance" means not following the rules. We have a bunch of different ways of checking that (looking at rejections is just one of them), but they all come down to doing exactly what [this guide](https://github.com/rainforestapp/tester-chrome-extension/wiki/Guide-Rules-&-Tester-Role) and [this guide](https://github.com/rainforestapp/tester-chrome-extension/wiki/Guide-Rules:-Confusing-Scenarios) are asking.

**Comment by qpPykT** [comment] 2016-08-24 15:44
@maciejgryka 
Ps: what about forum do you have any information about it? :)

**Comment by nerdatwork** [comment] 2016-08-24 15:45
@qpPykT What information do you need ?

**Comment by qpPykT** [comment] 2016-08-24 15:46
@nerdatwork 
when they open it for all testers?

**Comment by nerdatwork** [comment] 2016-08-24 15:47
It's still in experimental stage. When Rainforest has enough data they will decide whether to go forward with it or not.

**Comment by madeuser** [comment] 2016-08-24 19:07
@maciejgryka Thank you for your answer and your interest to help me and sort out this matter. I'll read again the wiki links that you posted and if I still consider that I was put to train wrongly I'll send you a ticket.
Good evening!

**Comment by bacomca** [comment] 2016-08-24 21:13
i think this is a bad ideal since more trainning tests = more "There are no virtual machines currently available" + "maximum user" errors

**Comment by sweeneyapps** [comment] 2016-08-24 23:13
I hate to ask..   any of you getting paid for the training jobs?   let me know.

**Comment by begsoon** [comment] 2016-08-24 23:16
@sweeneyapps ''Training tasks are paid like other tasks.''

**Comment by sweeneyapps** [comment] 2016-08-24 23:19
yup I know.. that's why I am asking.. because some of testers are saying they showing that they are not paid for the training days job.

**Comment by RezwanulHaque** [comment] 2016-08-24 23:45
Yes, I am also not receiving payment for training jobs. I have completed ~50 training jobs and no payment.

**Comment by sweeneyapps** [comment] 2016-08-25 00:06
@RezwanulHaque and all others who re not being paid..     Let Rainforest know about it here..      Use this link as a supporting evidence that Training jobs are paid job.  

https://github.com/rainforestapp/tester-chrome-extension/wiki/Training-Tasks

**Comment by nerdatwork** [comment] 2016-08-25 02:33
The jobs that have the "Training jobs (?)" in the center of the page **DO NOT PAY**. The wiki link that @sweeneyapps is referring is about the Rainforest's own jobs where you click on New Test or check schedules or check box to show the bar with duplicate, delete etc buttons. These are the **PAYING** tasks and they are also training you.

**Comment by uangonline** [comment] 2016-08-25 03:24
@sweeneyapps Yes, it's strange when the Wiki said that the training job paid, but actually not.

**Comment by irishclouds** [comment] 2016-08-25 03:59
I have just received a paid bonus for the training jobs made yesterday, no pay for the single job, but a bonus for 36 training jobs. No normal job for me yet. :(

**Comment by qpPykT** [comment] 2016-08-25 04:31
Now we have three kind of training jobs:

1) First type when the testers start working on the rf they have a few training jobs.
2) Second type when the testers working and get a couple training jobs every day.
3) The third type of training jobs when testers do not follow the instructions exactly. They get a cycle of training jobs as long as they can prove that they are worthy to receive regular tasks and follow the instructions exactly as required.

First and second types of training jobs are paid. The third type of training jobs is not paid and it's expected result.

**Comment by Profica** [comment] 2016-08-25 09:30
So :) .... what are the news, when will all be back in normal? :)

**Comment by irishclouds** [comment] 2016-08-25 10:07
For me today is back to normal job, i hope there isn't negative surprise in next hours-days.

**Comment by nerdatwork** [comment] 2016-08-25 13:15
@vladfuller If you are satisfied with the responses you got, you can close this thread.

**Comment by sweeneyapps** [comment] 2016-08-29 18:55
same here..   got into Training SandBox for no reason.

**Comment by madeuser** [comment] 2016-08-29 21:30
@sweeneyapps you're not alone, I keep receiving a training job and then a normal payed job. Normal job, training job, normal job, training job! If I miss the payed job (another user accepted the work before me) I receive a training job!  Oh, the joy! :)

**Comment by JrRandy** [comment] 2016-08-29 21:49
Yay!  Now I get to play in the sandbox :)

**Comment by sweeneyapps** [comment] 2016-08-29 22:59
nobody deserve this. I have done like 14 training jobs after doing nothing wrong. No rejections even no rejections on training jobs task. So I decided to turn off my chrome extension for the day and hopefully by tomorrow, I am getting paid job. Again, nobody deserve this at all. Also in USA, we do pay our workers on their training day. So Rainforest needs to go back to the drawing board and figure out to do this the legal way. And compensation all of us. Thank you for ur time to hear me out.

**Comment by Angelituss** [comment] 2016-09-08 16:29
Today I have reached more than 15 training lessons . Someone happens the same ??

**Comment by RezwanulHaque** [comment] 2016-09-08 16:52
Yes, I did have training jobs. Completed all the jobs successfully and getting normal task again.

**Closed** 2016-10-16 16:58 UTC
